import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { contentFileFingerprint } from '../src/content-inspection.js';
import { SaveService } from '../src/save-service.js';
import { Registry } from '../src/registry.js';
import { createResourceControl } from '../src/resource-control.js';
import { createDataWorkService } from '../src/ui/services/data-work-service.js';
import { createSavedWorkService } from '../src/ui/services/saved-work-service.js';
import { createTableWorkModule } from '../src/table-work-module.js';
import { MODULE_PROTOCOL_VERSION } from '../src/protocol.js';
import { renderDataWorkView } from '../src/ui/views/data-work-view.js';

const python = path.resolve('test/.tmp/v20-01-isolated-install/desktop-ui/venv/Scripts/python.exe');
const pythonRoot = path.resolve('python');
const pythonSourceRoot = path.resolve('python/src');
function runDataWork(args) {
  const argv = ['-m', 'atlas_content', 'data-work', '--file', args.filePath, '--expected-sha256', args.expectedSha256, '--action', args.action];
  if (args.requestPath) argv.push('--request', args.requestPath);
  if (args.outputPath) argv.push('--output', args.outputPath);
  if (args.sheet) argv.push('--sheet', args.sheet);
  const result = spawnSync(python, argv, { cwd: pythonRoot, encoding: 'utf8', timeout: 30000, maxBuffer: 8 * 1024 * 1024, env: { ...process.env, PYTHONPATH: [pythonSourceRoot, process.env.PYTHONPATH].filter(Boolean).join(path.delimiter), PYTHONUTF8: '1' } });
  if (result.error) throw result.error;
  if (result.status !== 0) throw new Error(result.stderr || result.stdout || `Python Data Work exited ${result.status}`);
  return JSON.parse(result.stdout);
}

test('Table Work trend compares adjacent date-only month periods and saves the same full monthly result', async (t) => {
  const root = fs.mkdtempSync(path.resolve('test/.tmp/data-work-trend-'));
  const workspace = path.join(root, 'workspace'); const projectPath = path.join(workspace, 'Traffic');
  const sourcePath = path.join(projectPath, 'Data', 'monthly.csv');
  fs.mkdirSync(path.dirname(sourcePath), { recursive: true }); fs.mkdirSync(path.join(projectPath, 'Results'), { recursive: true });
  const rows = ['service_date,amount'];
  for (let index = 0; index < 20; index += 1) rows.push('2026-01-15,10');
  for (let index = 0; index < 15; index += 1) rows.push('2026-02-15,20');
  for (let index = 0; index < 25; index += 1) rows.push('2026-03-15,10');
  for (let index = 0; index < 10; index += 1) rows.push('2026-04-15,30');
  rows.push('2026-02-01,', '2026-04-30,', '2026-05-01,99');
  const original = `${rows.join('\n')}\n`; fs.writeFileSync(sourcePath, original, 'utf8');
  const stateDir = path.join(root, 'state'); const registry = new Registry({ stateDir });
  const adopted = registry.adoptRoot({ rootPath: workspace, rootType: 'project_workspace', contentPolicy: 'bounded_content' });
  const created = registry.create({ name: 'Traffic', currentPath: 'Traffic' }); registry.attachRoot(created.project_id, { rootId: adopted.root_id, relativePath: 'Traffic', reason: 'Trend fixture.' });
  const control = createResourceControl({ stateDir, ledger: registry.ledger }); const project = { id: created.project_id, name: created.name };
  const resource = control.identify({ filePath: sourcePath, project });
  const dataWork = createDataWorkService({ stateDir, projectRoot: root, installationRoot: root, resourceControl: control, fingerprintFn: async (filePath) => contentFileFingerprint(filePath), runDataWorkFn: runDataWork });
  const saveService = new SaveService({ stateDir }); const savedWork = createSavedWorkService({ stateDir, saveService });
  const resolveProject = (projectId) => { const item = registry.list().find((candidate) => candidate.id === projectId && candidate.status === 'active'); if (!item) return null; const location = registry.show(projectId).location; return location?.root_path ? { project: { id: item.id, name: item.name, status: item.status }, location } : null; };
  const module = createTableWorkModule({ dataWork, savedWork, resolveProject });
  t.after(() => { saveService.dispose(); control.dispose(); registry.dispose(); fs.rmSync(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 20 }); });
  const invoke = (action, parameters = {}, work = null) => module.invoke({ protocol: MODULE_PROTOCOL_VERSION, module_id: 'atlas.table-work', project_id: project.id, ...(work ? { work } : {}), action, parameters });
  let work = (await invoke('start', { resource_ids: [resource.resource_id], caller: { actor: 'agent', tool: 'trend-fixture', client_run_id: 'trend-start' } })).data;
  work = (await invoke('prepare', {}, { session_id: work.session_id, base_revision: work.revision })).data;
  assert.equal(work.sources[0].status, 'ready');
  const mapping = work.sources[0].profile.profile.fields.map((field) => ({ source_key: work.sources[0].source_key, column: field.name, canonical: field.name }));
  work = (await invoke('align', { mapping }, { session_id: work.session_id, base_revision: work.revision })).data;
  work = (await invoke('recipe', { combine: 'concatenate', trend_date_field: 'service_date', trend_measure: 'amount', trend_formula: 'sum', trend_start_month: '2026-01', trend_current_start_month: '2026-03', trend_end_month: '2026-04', trend_unit: 'rides', trend_null_policy: 'exclude' }, { session_id: work.session_id, base_revision: work.revision })).data;
  assert.deepEqual(work.recipe.steps.find((step) => step.operation === 'trend-aggregate'), { operation: 'trend-aggregate', date_field: 'service_date', measure: 'amount', formula: 'sum', start_month: '2026-01', current_start_month: '2026-03', end_month: '2026-04', unit: 'rides', null_policy: 'exclude' });
  work = (await invoke('preview', {}, { session_id: work.session_id, base_revision: work.revision })).data;
  const host = await module.readPreview({ protocol: MODULE_PROTOCOL_VERSION, module_id: 'atlas.table-work', project_id: project.id, work: { session_id: work.session_id, base_revision: work.revision }, preview_revision: work.preview_revision });
  const trend = host.preview.trend_aggregation;
  assert.equal(work.preview_revision, work.revision);
  assert.deepEqual(trend.monthly_totals, [{ month: '2026-01', sum: 200 }, { month: '2026-02', sum: 300 }, { month: '2026-03', sum: 250 }, { month: '2026-04', sum: 300 }]);
  assert.deepEqual(trend.previous_period, { start_month: '2026-01', end_month: '2026-02', total: 500 });
  assert.deepEqual(trend.current_period, { start_month: '2026-03', end_month: '2026-04', total: 550 });
  assert.equal(trend.delta, 50); assert.equal(trend.growth_percent, 10);
  assert.equal(trend.included_rows, 70); assert.equal(trend.excluded_empty_rows, 2); assert.equal(trend.out_of_range_rows, 1);
  const html = renderDataWorkView({ mode: 'sources', session: work, project, back_href: `/projects/${project.id}/resources`, csrf: 'csrf-trend' }, { locale: 'en' });
  assert.match(html, /trend_date_field/u); assert.match(html, /trend_current_start_month/u); assert.match(html, /2026-01/u); assert.match(html, /2026-04/u); assert.match(html, /10%/u);
  assert.match(html, /Monthly trend/u);

  const prep = (await invoke('prepare-save', { folder: 'Results', file_name: 'monthly-trend.csv', format: 'csv' }, { session_id: work.session_id, base_revision: work.revision })).data;
  const saved = await invoke('confirm-save', { ...prep, folder: 'Results', file_name: 'monthly-trend.csv', format: 'csv', channel: 'work', request_key: 'trend-save', reason: 'Confirmed monthly trend.', caller: { actor: 'agent', tool: 'trend-fixture', client_run_id: 'trend-save' } }, { session_id: work.session_id, base_revision: work.revision });
  assert.equal(saved.data.status, 'executed');
  const output = fs.readFileSync(path.join(projectPath, 'Results', 'monthly-trend.csv'), 'utf8');
  for (const month of ['2026-01,200', '2026-02,300', '2026-03,250', '2026-04,300']) assert.ok(output.includes(month), `Missing monthly total ${month}`);
  assert.equal(contentFileFingerprint(sourcePath).sha256, resource.evidence.sha256); assert.equal(fs.readFileSync(sourcePath, 'utf8'), original);
  fs.appendFileSync(sourcePath, '2026-01-20,1\n', 'utf8');
  await assert.rejects(invoke('preview', {}, { session_id: work.session_id, base_revision: work.revision }), { code: 'ATLAS_STATE_CONFLICT' });
  await assert.rejects(invoke('prepare-save', { folder: 'Results', file_name: 'stale-trend.csv', format: 'csv' }, { session_id: work.session_id, base_revision: work.revision }), { code: 'ATLAS_STATE_CONFLICT' });
  assert.equal(fs.existsSync(path.join(projectPath, 'Results', 'stale-trend.csv')), false);
});
