import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { contentFileFingerprint } from '../src/content-inspection.js';
import { SaveService } from '../src/save-service.js';
import { Registry } from '../src/registry.js';
import { createResourceControl } from '../src/resource-control.js';
import { createDataWorkService } from '../src/ui/services/data-work-service.js';
import { createSavedWorkService } from '../src/ui/services/saved-work-service.js';
import { createTableWorkModule } from '../src/table-work-module.js';
import { MODULE_PROTOCOL_VERSION } from '../src/protocol.js';

const python = (process.env.ATLAS_TEST_PYTHON ?? process.env.ATLAS_CONTENT_PYTHON ?? path.resolve('test/.tmp/v20-01-isolated-install/desktop-ui/venv/Scripts/python.exe'));
const pythonRoot = path.resolve('python'); const pythonSourceRoot = path.resolve('python/src');
function runDataWork(args) {
  const argv = ['-m', 'atlas_content', 'data-work', '--file', args.filePath, '--expected-sha256', args.expectedSha256, '--action', args.action];
  if (args.requestPath) argv.push('--request', args.requestPath);
  if (args.outputPath) argv.push('--output', args.outputPath);
  if (args.sheet) argv.push('--sheet', args.sheet);
  const result = spawnSync(python, argv, { cwd: pythonRoot, encoding: 'utf8', timeout: 30000, maxBuffer: 8 * 1024 * 1024, env: { ...process.env, PYTHONPATH: [pythonSourceRoot, process.env.PYTHONPATH].filter(Boolean).join(path.delimiter), PYTHONUTF8: '1' } });
  if (result.error) throw result.error;
  if (result.status !== 0) throw new Error(result.stderr || result.stdout || `Python Data Work exited ${result.status}`);
  return JSON.parse(result.stdout);
}

test('Table Work focus persists category filter, pages processed detail rows and clears back to original totals', async (t) => {
  const root = fs.mkdtempSync(path.resolve('test/.tmp/data-work-focus-'));
  const workspace = path.join(root, 'workspace'); const projectPath = path.join(workspace, 'Traffic');
  const sourcePath = path.join(projectPath, 'Data', 'volume.csv');
  fs.mkdirSync(path.dirname(sourcePath), { recursive: true }); fs.mkdirSync(path.join(projectPath, 'Results'), { recursive: true });
  const rows = ['district,amount'];
  for (let index = 0; index < 25; index += 1) rows.push('North,12.50');
  for (let index = 0; index < 20; index += 1) rows.push('South,7.25');
  for (let index = 0; index < 15; index += 1) rows.push('East,4.00');
  rows.push('North,', 'South,', ',0'); const original = `${rows.join('\n')}\n`; fs.writeFileSync(sourcePath, original, 'utf8');
  const stateDir = path.join(root, 'state'); const registry = new Registry({ stateDir });
  const adopted = registry.adoptRoot({ rootPath: workspace, rootType: 'project_workspace', contentPolicy: 'bounded_content' });
  const created = registry.create({ name: 'Traffic', currentPath: 'Traffic' }); registry.attachRoot(created.project_id, { rootId: adopted.root_id, relativePath: 'Traffic', reason: 'Focus fixture.' });
  fs.mkdirSync(path.join(workspace, 'Other'), { recursive: true });
  const otherProject = registry.create({ name: 'Other', currentPath: 'Other' }); registry.attachRoot(otherProject.project_id, { rootId: adopted.root_id, relativePath: 'Other', reason: 'Cross-project boundary fixture.' });
  const control = createResourceControl({ stateDir, ledger: registry.ledger }); const project = { id: created.project_id, name: created.name };
  const resource = control.identify({ filePath: sourcePath, project });
  const dataWork = createDataWorkService({ stateDir, projectRoot: root, installationRoot: root, resourceControl: control, fingerprintFn: async (filePath) => contentFileFingerprint(filePath), runDataWorkFn: runDataWork });
  const saveService = new SaveService({ stateDir }); const savedWork = createSavedWorkService({ stateDir, saveService });
  const resolveProject = (projectId) => { const item = registry.list().find((candidate) => candidate.id === projectId && candidate.status === 'active'); if (!item) return null; const location = registry.show(projectId).location; return location?.root_path ? { project: { id: item.id, name: item.name, status: item.status }, location } : null; };
  const module = createTableWorkModule({ dataWork, savedWork, resolveProject });
  t.after(() => { saveService.dispose(); control.dispose(); registry.dispose(); fs.rmSync(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 20 }); });
  const invoke = (action, parameters = {}, baseRevision = null, sessionId = null) => module.invoke({ protocol: MODULE_PROTOCOL_VERSION, module_id: 'atlas.table-work', project_id: project.id, ...(sessionId ? { work: { session_id: sessionId, base_revision: baseRevision } } : {}), action, parameters });
  let work = (await invoke('start', { resource_ids: [resource.resource_id], caller: { actor: 'agent', tool: 'focus-fixture', client_run_id: 'focus-start' } })).data;
  work = (await invoke('prepare', {}, work.revision, work.session_id)).data;
  const mapping = work.sources[0].profile.profile.fields.map((field) => ({ source_key: work.sources[0].source_key, column: field.name, canonical: field.name }));
  work = (await invoke('align', { mapping }, work.revision, work.session_id)).data;
  work = (await invoke('recipe', { combine: 'concatenate', filter_column: 'district', filter_operator: 'not_contains', filter_value: 'West', aggregate_dimension: 'district', aggregate_measure: 'amount', aggregate_formula: 'sum', aggregate_unit: 'vehicles', aggregate_null_policy: 'exclude' }, work.revision, work.session_id)).data;
  work = (await invoke('preview', {}, work.revision, work.session_id)).data;
  assert.equal(work.preview.aggregation.grand_total, 517.5);
  assert.ok(work.preview.aggregation.groups.some((group) => group.value === '' && group.sum === 0));
  const emptyFocus = (await invoke('focus', { category: '', caller: { tool: 'focus-fixture', client_run_id: 'focus-empty' } }, work.revision, work.session_id)).data;
  work = (await invoke('preview', {}, emptyFocus.revision, work.session_id)).data;
  assert.deepEqual(work.preview.aggregation.groups.map((group) => group.value), ['']);
  const emptyDetails = (await invoke('details', { offset: 0, limit: 10 }, work.revision, work.session_id)).data;
  assert.equal(emptyDetails.total, 1);
  const emptyCleared = (await invoke('focus', { clear: true, caller: { tool: 'focus-fixture', client_run_id: 'focus-empty-clear' } }, work.revision, work.session_id)).data;
  work = (await invoke('preview', {}, emptyCleared.revision, work.session_id)).data;
  const oldPreviewRevision = work.preview_revision;
  await assert.rejects(invoke('focus', { category: 'Not a current aggregate category', caller: { tool: 'focus-fixture', client_run_id: 'focus-invalid' } }, work.revision, work.session_id), { code: 'ATLAS_STATE_CONFLICT' });
  const focused = await invoke('focus', { category: 'North', caller: { tool: 'focus-fixture', client_run_id: 'focus-north' } }, work.revision, work.session_id);
  assert.equal(focused.data.revision, work.revision + 1);
  assert.equal(focused.data.focus.value, 'North');
  assert.equal(focused.data.recipe.steps.filter((step) => step.focus).length, 1);
  assert.equal(focused.data.recipe.steps.find((step) => step.focus).operation, 'filter');
  await assert.rejects(module.readPreview({ protocol: MODULE_PROTOCOL_VERSION, module_id: 'atlas.table-work', project_id: project.id, work: { session_id: work.session_id, base_revision: work.revision }, preview_revision: oldPreviewRevision }), { code: 'ATLAS_STATE_CONFLICT' });
  work = (await invoke('preview', {}, focused.data.revision, work.session_id)).data;
  assert.equal(work.preview.aggregation.grand_total, 312.5);
  assert.deepEqual(work.preview.aggregation.groups.map((item) => item.value), ['North']);
  const first = (await invoke('details', { offset: 0, limit: 10 }, work.revision, work.session_id)).data;
  const second = (await invoke('details', { offset: first.next_offset, limit: 10 }, work.revision, work.session_id)).data;
  await assert.rejects(invoke('details', { offset: 0, limit: 51 }, work.revision, work.session_id), { code: 'ATLAS_MODULE_INVALID_REQUEST' });
  await assert.rejects(module.invoke({ protocol: MODULE_PROTOCOL_VERSION, module_id: 'atlas.table-work', project_id: otherProject.project_id, work: { session_id: work.session_id, base_revision: work.revision }, action: 'details', parameters: { offset: 0, limit: 10 } }), { code: 'ATLAS_MODULE_PROJECT_MISMATCH' });
  await assert.rejects(invoke('details', { offset: 0, limit: 10 }, work.revision - 1, work.session_id), { code: 'ATLAS_STATE_CONFLICT' });
  assert.equal(first.total, 25); assert.equal(first.rows.length, 10); assert.equal(first.next_offset, 10); assert.equal(first.complete, false);
  assert.equal(second.rows.length, 10); assert.equal(second.offset, 10); assert.equal(second.total, 25);
  assert.equal(first.revision, work.revision); assert.equal(first.preview_revision, work.preview_revision);
  assert.deepEqual(first.sources, [{ resource_id: resource.resource_id, sha256: resource.evidence.sha256 }]);
  assert.ok(first.rows.every((row) => row[0] === 'North'));
  const cleared = (await invoke('focus', { clear: true, caller: { tool: 'focus-fixture', client_run_id: 'focus-clear' } }, work.revision, work.session_id)).data;
  assert.equal(cleared.revision, work.revision + 1);
  assert.equal(cleared.recipe.steps.filter((step) => step.focus).length, 0);
  assert.deepEqual(cleared.recipe.steps.find((step) => step.operation === 'filter'), { operation: 'filter', column: 'district', operator: 'not_contains', value: 'West' });
  work = (await invoke('preview', {}, cleared.revision, work.session_id)).data;
  assert.equal(work.preview.aggregation.grand_total, 517.5);
  const stage = (await invoke('prepare-save', { folder: 'Results', file_name: 'all-districts.csv', format: 'csv' }, work.revision, work.session_id)).data;
  const saved = await invoke('confirm-save', { ...stage, folder: 'Results', file_name: 'all-districts.csv', format: 'csv', channel: 'work', request_key: 'focus-clear-save', reason: 'Fixture participant confirmed the full aggregate.', caller: { actor: 'agent', tool: 'focus-fixture', client_run_id: 'focus-clear-save' } }, stage.revision, work.session_id);
  assert.equal(saved.data.status, 'executed');
  const savedCsv = fs.readFileSync(path.join(projectPath, 'Results', 'all-districts.csv'), 'utf8');
  assert.match(savedCsv, /North,312\.5/u);
  assert.match(savedCsv, /South,145/u);
  assert.match(savedCsv, /East,60/u);
  assert.equal(savedCsv.trim().split(/\r?\n/u).slice(1).reduce((sum, line) => sum + Number(line.slice(line.lastIndexOf(',') + 1)), 0), 517.5);
  assert.equal(contentFileFingerprint(sourcePath).sha256, resource.evidence.sha256);
  assert.equal(fs.readFileSync(sourcePath, 'utf8'), original);
  fs.writeFileSync(sourcePath, original.replace('North,12.50', 'North,13.50'), 'utf8');
  await assert.rejects(invoke('details', { offset: 0, limit: 10 }, work.revision, work.session_id), { code: 'ATLAS_STATE_CONFLICT' });
});
