import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { contentFileFingerprint } from '../src/content-inspection.js';
import { Registry } from '../src/registry.js';
import { createResourceControl } from '../src/resource-control.js';
import { createDataWorkService } from '../src/ui/services/data-work-service.js';

function fixture(t) {
  const root = fs.mkdtempSync(path.join(path.resolve('test', '.tmp'), 'data-work-change-review-r2-')); const workspace = path.join(root, 'workspace'); const projectRoot = path.join(workspace, 'Project'); fs.mkdirSync(path.join(projectRoot, 'Data'), { recursive: true });
  const paths = ['one', 'two', 'three'].map((name) => { const filePath = path.join(projectRoot, 'Data', `${name}.csv`); fs.writeFileSync(filePath, 'name,value\nold,1\nold2,2\n'); return filePath; });
  const stateDir = path.join(root, 'state'); const registry = new Registry({ stateDir }); const adopted = registry.adoptRoot({ rootPath: workspace, rootType: 'project_workspace', contentPolicy: 'bounded_content' }); const created = registry.create({ name: 'Project', currentPath: 'Project' }); registry.attachRoot(created.project_id, { rootId: adopted.root_id, relativePath: 'Project', reason: 'R2 change review fixture.' }); const control = createResourceControl({ stateDir, ledger: registry.ledger }); const project = { id: created.project_id, name: created.name }; const resources = paths.map((filePath) => control.identify({ filePath, project }));
  const service = createDataWorkService({ stateDir, projectRoot: root, installationRoot: root, resourceControl: control, fingerprintFn: async (filePath) => contentFileFingerprint(filePath), runDataWorkFn: async ({ filePath, action }) => { if (action !== 'profile') throw new Error(`Unexpected R2 action: ${action}`); const [header, ...rows] = fs.readFileSync(filePath, 'utf8').trim().split(/\r?\n/u); return { status: 'ready', profile: { fields: header.split(',').map((name) => ({ name, inferred_type: 'text' })), sample: { columns: header.split(','), rows: rows.slice(0, 2).map((row) => row.split(',')) } }, processor: { version: 'r2-test' } }; } });
  t.after(() => { control.dispose(); registry.dispose(); fs.rmSync(root, { recursive: true, force: true }); }); return { root, stateDir, registry, control, service, project, paths, resources };
}

function workFixture(f) {
  let work = f.service.createProjectSession(f.project, {}, [], { intent: 'R2 change review', caller: { actor: 'agent', tool: 'test', client_run_id: 'r2-create' } }); for (const resource of f.resources) work = f.service.addSource(work.session_id, resource.resource_id, { baseRevision: work.revision });
  for (const [index, source] of work.sources.entries()) f.registry.ledger.workSessions.updateSource(work.session_id, source.source_key, { fingerprint: contentFileFingerprint(f.paths[index]), profile: { profile: { fields: [{ name: 'name', inferred_type: 'text' }, { name: 'value', inferred_type: 'text' }], sample: { columns: ['name', 'value'], rows: [['old', '1'], ['old2', '2']] } } }, processorVersion: 'r2-test', status: 'ready' }, new Date().toISOString());
  const mapping = work.sources.flatMap((source) => [{ source_key: source.source_key, column: 'name', canonical: `${source.ordinal}_name` }, { source_key: source.source_key, column: 'value', canonical: `${source.ordinal}_value` }]); work = f.service.confirmMapping(work.session_id, mapping, { baseRevision: work.revision }); work = f.service.updateRecipe(work.session_id, { combine: 'concatenate', steps: [{ operation: 'validate' }] }, { baseRevision: work.revision }); f.registry.ledger.workSessions.setPreview(work.session_id, { marker: 'r2-preview' }, work.revision, new Date().toISOString()); f.registry.ledger.workSessions.setLatestSave(work.session_id, 'SAVE-r2-prior', new Date().toISOString()); return f.registry.ledger.workSessions.byId(work.session_id);
}

test('R2 validateSources returns one central change review with bounded before/after evidence', async (t) => {
  const f = fixture(t); const before = workFixture(f); fs.appendFileSync(f.paths[0], 'new,9\n'); fs.appendFileSync(f.paths[1], 'newer,8\n'); const reviewed = await f.service.validateSources(before.session_id); assert.equal(reviewed.change_review.status, 'needs_review'); assert.equal(reviewed.change_review.counts.changed, 2); assert.equal(reviewed.change_review.items.length, 2); assert.ok(reviewed.change_review.items.every((item) => item.before && item.after && (item.before.rows || item.before.values) && (item.after.rows || item.after.values))); assert.equal(reviewed.change_review.work.session_id, before.session_id); assert.equal(reviewed.change_review.work.revision, reviewed.revision); assert.equal(reviewed.change_review.work.latest_save_id, 'SAVE-r2-prior'); assert.match(reviewed.change_review.note, /Hash.*backup|not.*backup/iu);
});

test('R2 reconcileSources use-current applies compatible changes once and rebinds only affected mapping hashes', async (t) => {
  const f = fixture(t); const before = workFixture(f); fs.appendFileSync(f.paths[0], 'new,9\n'); fs.appendFileSync(f.paths[1], 'newer,8\n'); const checked = await f.service.validateSources(before.session_id); const reconciled = await f.service.reconcileSources(before.session_id, checked.sources.slice(0, 2).map((source) => source.source_key), 'use-current', { baseRevision: checked.revision }); assert.equal(reconciled.revision, checked.revision + 1); assert.equal(reconciled.mapping_complete, true); assert.equal(reconciled.sources.slice(0, 2).every((source) => source.status === 'ready'), true); assert.deepEqual(reconciled.recipe, before.recipe); assert.equal(reconciled.latest_save_id, before.latest_save_id); assert.equal(reconciled.preview, null); assert.ok(reconciled.mapping.filter((item) => item.source_key === reconciled.sources[0].source_key || item.source_key === reconciled.sources[1].source_key).every((item) => item.source_sha256));
});

test('R2 mixed reconcile marks only the structural mismatch and preserves unaffected mapping basis', async (t) => {
  const f = fixture(t); const before = workFixture(f); fs.appendFileSync(f.paths[0], 'new,9\n'); fs.writeFileSync(f.paths[1], 'other,value\nnewer,8\n'); const checked = await f.service.validateSources(before.session_id); const reconciled = await f.service.reconcileSources(before.session_id, checked.sources.slice(0, 2).map((source) => source.source_key), 'use-current', { baseRevision: checked.revision }); assert.equal(reconciled.sources[0].status, 'ready'); assert.equal(reconciled.sources[1].status, 'mapping_required'); assert.match(reconciled.sources[1].error_message ?? '', /field|column|mapping|mismatch/iu); assert.equal(reconciled.sources[2].status, 'ready'); assert.ok(reconciled.mapping.some((item) => item.source_key === reconciled.sources[2].source_key && item.source_sha256 === before.mapping.find((entry) => entry.source_key === item.source_key)?.source_sha256));
});

test('R2 reconcileSources pin-recorded batches changed Sources in one revision as contained', async (t) => {
  const f = fixture(t); const before = workFixture(f); fs.appendFileSync(f.paths[0], 'new,9\n'); fs.appendFileSync(f.paths[1], 'newer,8\n'); const checked = await f.service.validateSources(before.session_id); const pinned = await f.service.reconcileSources(before.session_id, checked.sources.slice(0, 2).map((source) => source.source_key), 'pin-recorded', { baseRevision: checked.revision }); assert.equal(pinned.revision, checked.revision + 1); assert.equal(pinned.sources.slice(0, 2).every((source) => source.version_policy === 'pinned_version'), true); assert.match(pinned.freshness.label, /contained|pinned/iu); assert.equal(pinned.latest_save_id, before.latest_save_id); const reviewed = await f.service.validateSources(before.session_id); assert.equal(reviewed.change_review.status, 'fresh'); assert.equal(reviewed.change_review.counts.total, 0); assert.deepEqual(reviewed.change_review.items, []);
});
