import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { Registry } from '../src/registry.js';
import { Intake } from '../src/intake.js';
import { createResourceControl } from '../src/resource-control.js';
import { startAtlasUiServer } from '../src/ui-server.js';

test('Modules page reviews exact package bytes, installs disabled, and prepares the same Save flow after enable', async (t) => {
  const root = fs.mkdtempSync(path.join(path.resolve('test/.tmp'), 'local-module-ui-'));
  const stateDir = path.join(root, 'state'); const workspace = path.join(root, 'workspace'); const projectPath = path.join(workspace, 'A');
  const data = path.join(projectPath, 'Data'); const results = path.join(projectPath, 'Results');
  fs.mkdirSync(data, { recursive: true }); fs.mkdirSync(results, { recursive: true });
  const sourcePath = path.join(data, 'note.txt'); fs.writeFileSync(sourcePath, 'hello Atlas', 'utf8');
  const packagePath = path.join(root, 'transform.json');
  const manifest = { module_id: 'local.ui-transform', module_version: '1.0.0', adapter: 'text_transform_v1', permissions: ['node_full_account'], entry_source: "globalThis.localUiModuleRan = true; export function transform(text) { return `UI:${text.toUpperCase()}`; }" };
  fs.writeFileSync(packagePath, JSON.stringify(manifest), 'utf8');
  const packageHash = crypto.createHash('sha256').update(fs.readFileSync(packagePath)).digest('hex');
  const registry = new Registry({ stateDir });
  const rootInfo = registry.adoptRoot({ rootPath: workspace, rootType: 'project_workspace', contentPolicy: 'structure_only' });
  const created = registry.create({ name: 'A', currentPath: 'A' });
  registry.attachRoot(created.project_id, { rootId: rootInfo.root_id, relativePath: 'A', reason: 'Local Module UI fixture.' });
  const control = createResourceControl({ stateDir, ledger: registry.ledger, registry });
  const resource = control.identify({ filePath: sourcePath, project: { id: created.project_id, name: 'A' } });
  const otherPath = path.join(workspace, 'B', 'Data', 'other.txt');
  fs.mkdirSync(path.dirname(otherPath), { recursive: true }); fs.writeFileSync(otherPath, 'other Project', 'utf8');
  const other = registry.create({ name: 'B', currentPath: 'B' });
  registry.attachRoot(other.project_id, { rootId: rootInfo.root_id, relativePath: 'B', reason: 'Cross-Project local Module fixture.' });
  const otherResource = control.identify({ filePath: otherPath, project: { id: other.project_id, name: 'B' } });
  const intake = new Intake({ stateDir });
  let server;
  t.after(async () => { if (server) await server.close(); intake.dispose(); control.dispose(); registry.dispose(); fs.rmSync(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 20 }); });
  server = await startAtlasUiServer({ stateDir, registry, intake, rules: {}, runtime: {}, projectRoot: root, installationRoot: root, resourceControl: control });
  const getModules = async () => (await fetch(new URL('/modules', server.workspace_url))).text();
  let html = await getModules();
  const csrf = html.match(/name="csrf" value="([a-f0-9]+)"/u)?.[1]; assert.ok(csrf);
  const post = (route, fields) => fetch(new URL(route, server.workspace_url), { method: 'POST', redirect: 'manual', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ csrf, ...fields }) });
  let response = await post('/modules/package-preview', { file_path: packagePath });
  assert.equal(response.status, 200); html = await response.text();
  assert.match(html, new RegExp(packageHash, 'u')); assert.match(html, /not been executed|尚未执行/u);
  assert.equal(globalThis.localUiModuleRan, undefined);
  const token = html.match(/name="preview_token" value="([^"]+)"/u)?.[1]; assert.ok(token);
  response = await post('/modules/package-install', { preview_token: token, expected_sha256: packageHash, expected_revision: '0', request_key: 'ui-install-1' });
  assert.equal(response.status, 303); html = await getModules(); assert.match(html, /Disabled|已停用/u);
  const localRevision = html.match(/name="expected_revision" value="1"/u); assert.ok(localRevision);
  response = await post('/modules/local-preview', { module_id: manifest.module_id, project_id: created.project_id, resource_id: resource.resource_id, target: 'A/Results/out.txt' });
  assert.equal(response.status, 409); assert.equal(globalThis.localUiModuleRan, undefined);
  response = await post('/modules/local-change', { module_id: manifest.module_id, action: 'enable', expected_revision: '1', request_key: 'ui-enable-1' });
  assert.equal(response.status, 303);
  response = await post('/modules/local-preview', { module_id: manifest.module_id, project_id: created.project_id, resource_id: resource.resource_id, target: 'A/Results/out.txt' });
  assert.equal(response.status, 200); html = await response.text(); assert.match(html, /UI:HELLO ATLAS/u);
  assert.equal(globalThis.localUiModuleRan, true);
  response = await post('/modules/local-preview', { module_id: manifest.module_id, project_id: created.project_id, resource_id: otherResource.resource_id, target: 'A/Results/other.txt' });
  assert.equal(response.status, 409); assert.equal(fs.existsSync(path.join(results, 'other.txt')), false);
  response = await post('/modules/local-save', { module_id: manifest.module_id, project_id: created.project_id, resource_id: resource.resource_id, target: '../outside.txt', request_key: 'ui-escape' });
  assert.equal(response.status, 409); assert.equal(fs.existsSync(path.join(root, 'outside.txt')), false);
  response = await post('/modules/local-save', { module_id: manifest.module_id, project_id: created.project_id, resource_id: resource.resource_id, target: 'A/Results/out.txt', request_key: 'ui-local-save-1' });
  assert.equal(response.status, 303); const saveHref = response.headers.get('location'); assert.match(saveHref, /^\/saves\/SAV-/u);
  response = await fetch(new URL(saveHref, server.workspace_url)); assert.equal(response.status, 200); html = await response.text();
  assert.match(html, /UI:HELLO ATLAS/u);
  const previewRevision = html.match(/name="preview_revision" value="([^"]+)"/u)?.[1]; assert.ok(previewRevision);
  response = await fetch(new URL(`${saveHref}/execute`, server.workspace_url), { method: 'POST', redirect: 'manual', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ csrf, preview_revision: previewRevision }) });
  assert.equal(response.status, 303);
  assert.equal(fs.readFileSync(path.join(results, 'out.txt'), 'utf8'), 'UI:HELLO ATLAS');
  response = await fetch(new URL(saveHref, server.workspace_url)); assert.equal(response.status, 200); html = await response.text();
  assert.match(html, /Saved and verified|已保存并验证/u);
});
