import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { Registry } from '../src/registry.js';
import { ResourceControl } from '../src/resource-control.js';
import { Intake } from '../src/intake.js';
import { startAtlasUiServer } from '../src/ui-server.js';

test('UI partitions two existing folders in place, opens both Projects, and restores boundaries with Undo', async t => {
 const fixture=fs.mkdtempSync(path.resolve('test/.tmp/membership-partition-ui-'));
 const stateDir=path.join(fixture,'state');const workspace=path.join(fixture,'workspace');const originalRoot=path.join(workspace,'原项目');
 const retainedPath=path.join(originalRoot,'交付');const splitPath=path.join(originalRoot,'研究');
 fs.mkdirSync(retainedPath,{recursive:true});fs.mkdirSync(splitPath);
 const retainedFile=path.join(retainedPath,'成果.md');const splitFile=path.join(splitPath,'说明.md');
 fs.writeFileSync(retainedFile,'# Retained content\n');fs.writeFileSync(splitFile,'# Split content\n');
 const registry=new Registry({stateDir});const root=registry.adoptRoot({rootPath:workspace,rootType:'project_workspace',contentPolicy:'bounded_content'});
 const source=registry.create({name:'原项目',currentPath:'原项目'});registry.attachRoot(source.project_id,{rootId:root.root_id,relativePath:'原项目',reason:'Partition UI fixture'});
 const control=new ResourceControl({stateDir,registry});
 const retained=control.identify({filePath:retainedFile,project:registry.show(source.project_id).project});const split=control.identify({filePath:splitFile,project:registry.show(source.project_id).project});
 const intake=new Intake({stateDir});const server=await startAtlasUiServer({stateDir,registry,intake,resourceControl:control,projectRoot:workspace,installationRoot:workspace});
 t.after(async()=>{await server.close();intake.dispose();control.dispose();registry.dispose();});
 const route=`/projects/${source.project_id}/membership`;
 const get=async href=>fetch(new URL(href,server.workspace_url));
 const post=async(href,form)=>fetch(new URL(href,server.workspace_url),{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(form),redirect:'manual'});
 const hidden=(html,name)=>{const match=html.match(new RegExp(`name="${name}" value="([^"]*)"`,'u'));assert.ok(match,`missing ${name}`);return match[1];};
 const unchanged=()=>{assert.equal(fs.readFileSync(retainedFile,'utf8'),'# Retained content\n');assert.equal(fs.readFileSync(splitFile,'utf8'),'# Split content\n');};
 const initial=await get(route);assert.equal(initial.status,200);const chooser=await initial.text();assert.match(chooser,/partition_existing/u);
 const form={csrf:hidden(chooser,'csrf'),operation:'split',mode:'partition_existing',retained_relative_path:'交付',source_relative_path:'研究',new_project_name:'研究项目',request_key:'partition-ui-preview'};
 assert.equal((await post(`${route}/prepare`,{...form,csrf:'wrong'})).status,403);
 const prepared=await post(`${route}/prepare`,form);assert.equal(prepared.status,303,await prepared.text());
 const receipt=prepared.headers.get('location');const previewResponse=await get(receipt);assert.equal(previewResponse.status,200);const preview=await previewResponse.text();
 assert.match(preview,/Confirm Project boundary changes/u);assert.match(preview,/No files move/u);
 assert.match(preview,/原项目\/交付/u);assert.match(preview,/原项目\/研究/u);unchanged();assert.equal(registry.list().length,1);
 assert.equal(registry.show(source.project_id).location.relative_path,'原项目');
 const bound={csrf:hidden(preview,'csrf'),expected_revision:hidden(preview,'expected_revision'),expected_digest:hidden(preview,'expected_digest'),request_key:'partition-ui-confirm'};
 assert.equal((await post(`${receipt}/execute`,{...bound,expected_digest:'stale'})).status,409);
 assert.equal((await post(`${receipt}/execute`,bound)).status,303);unchanged();
 const appliedResponse=await get(receipt);assert.equal(appliedResponse.status,200);const applied=await appliedResponse.text();
 assert.match(applied,/Project boundaries changed/u);assert.doesNotMatch(applied,/document-updates\/repair/u);
 const target=registry.list().find(item=>item.name==='研究项目');assert.ok(target);
 assert.ok(applied.includes(`href="/projects/${target.id}"`));assert.ok(applied.includes(`href="/projects/${source.project_id}"`));
 assert.equal(registry.show(source.project_id).location.relative_path,'原项目/交付');assert.equal(registry.show(target.id).location.relative_path,'原项目/研究');
 assert.equal(control.projectResource(source.project_id,retained.resource_id).locations.find(item=>item.status==='active').path,retainedFile);
 assert.equal(control.projectResource(target.id,split.resource_id).locations.find(item=>item.status==='active').path,splitFile);
 const targetRead=await get(`/projects/${target.id}/resources/read?resource_id=${split.resource_id}`);assert.equal(targetRead.status,200);assert.match(await targetRead.text(),/Split content/u);
 const retainedRead=await get(`/projects/${source.project_id}/resources/read?resource_id=${retained.resource_id}`);assert.equal(retainedRead.status,200);assert.match(await retainedRead.text(),/Retained content/u);
 assert.equal((await post(`${receipt}/undo`,{...bound,request_key:'partition-ui-stale-undo'})).status,409);
 const undo=await post(`${receipt}/undo`,{csrf:hidden(applied,'csrf'),expected_revision:hidden(applied,'expected_revision'),expected_digest:hidden(applied,'expected_digest'),request_key:'partition-ui-undo'});
 assert.equal(undo.status,303,await undo.text());unchanged();assert.equal(registry.show(source.project_id).location.relative_path,'原项目');
 assert.equal(registry.show(target.id).project.status,'archived');assert.equal(control.projectResource(source.project_id,split.resource_id).resource_id,split.resource_id);
 assert.match(await(await get(receipt)).text(),/Project boundaries restored/u);
});

test('UI previews and confirms a split, reads the same Resource in its new Project, and safely undoes', async t => {
 const base=fs.mkdtempSync(path.resolve('test/.tmp/membership-ui-'));
 const stateDir=path.join(base,'state'); const workspace=path.join(base,'workspace');
 const source=path.join(workspace,'原项目');fs.mkdirSync(path.join(source,'研究'),{recursive:true});
 fs.writeFileSync(path.join(source,'研究','说明.md'),'# Same Resource\n');fs.writeFileSync(path.join(source,'保留.txt'),'stay\n');
 const registry=new Registry({stateDir});const root=registry.adoptRoot({rootPath:workspace,rootType:'project_workspace',contentPolicy:'bounded_content'});
 const project=registry.create({name:'原项目',currentPath:'原项目'});registry.attachRoot(project.project_id,{rootId:root.root_id,relativePath:'原项目',reason:'Membership fixture'});
 const control=new ResourceControl({stateDir,registry});const resource=control.identify({filePath:path.join(source,'研究','说明.md'),project:registry.show(project.project_id).project});
 const intake=new Intake({stateDir});const server=await startAtlasUiServer({stateDir,registry,intake,resourceControl:control,projectRoot:workspace,installationRoot:workspace});
 t.after(async()=>{await server.close();intake.dispose();control.dispose();registry.dispose();});
 const route=`/projects/${project.project_id}/membership`;
 const get=async url=>fetch(new URL(url,server.workspace_url));
 const post=async(url,form)=>fetch(new URL(url,server.workspace_url),{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(form),redirect:'manual'});
 const hidden=(html,name)=>{const match=html.match(new RegExp(`name="${name}" value="([^"]*)"`,'u'));assert.ok(match,`missing ${name}`);return match[1];};
 const first=await get(route);assert.equal(first.status,200);const start=await first.text();
 const prepared=await post(`${route}/prepare`,{csrf:hidden(start,'csrf'),operation:'split',source_relative_path:'研究',new_project_name:'研究项目',target_relative_path:'研究项目',request_key:'ui-split'});
 assert.equal(prepared.status,303,await prepared.text());const previewHref=prepared.headers.get('location');const preview=await(await get(previewHref)).text();
 assert.equal(fs.existsSync(path.join(workspace,'研究项目')),false);assert.equal(registry.list().length,1);
 assert.match(preview,/Confirm file and membership changes/u);
 const request={csrf:hidden(preview,'csrf'),expected_revision:hidden(preview,'expected_revision'),expected_digest:hidden(preview,'expected_digest'),request_key:'ui-confirm'};
 assert.equal((await post(`${previewHref}/execute`,{...request,csrf:'wrong'})).status,403);
 const execute=await post(`${previewHref}/execute`,request);assert.equal(execute.status,303,await execute.text());
 assert.equal((await post(`${previewHref}/execute`,request)).status,303);
 const result=await(await get(previewHref)).text();assert.match(result,/Files and membership changed/u);
 const target=registry.list().find(p=>p.name==='研究项目');assert.ok(target);
 assert.equal(control.projectResource(target.id,resource.resource_id).resource_id,resource.resource_id);
 const read=await get(`/projects/${target.id}/resources/read?resource_id=${resource.resource_id}`);assert.equal(read.status,200);assert.match(await read.text(),/Same Resource/u);
 assert.equal(fs.readFileSync(path.join(source,'保留.txt'),'utf8'),'stay\n');
 const stale=await post(`${previewHref}/undo`,{...request,request_key:'stale-undo'});assert.equal(stale.status,409);
 const undo=await post(`${previewHref}/undo`,{csrf:hidden(result,'csrf'),expected_revision:hidden(result,'expected_revision'),expected_digest:hidden(result,'expected_digest'),request_key:'ui-undo'});
 assert.equal(undo.status,303,await undo.text());assert.equal(fs.readFileSync(path.join(source,'研究','说明.md'),'utf8'),'# Same Resource\n');
 assert.match(await(await get(previewHref)).text(),/Change undone/u);
});

test('UI merges a whole Project and keeps its receipt and Undo reachable after the source becomes merged', async t => {
 const base=fs.mkdtempSync(path.resolve('test/.tmp/membership-merge-ui-'));
 const stateDir=path.join(base,'state'); const workspace=path.join(base,'workspace');
 const source=path.join(workspace,'原项目'); const destination=path.join(workspace,'目标项目');
 fs.mkdirSync(source,{recursive:true}); fs.mkdirSync(destination);
 fs.writeFileSync(path.join(source,'说明.md'),'# Merge preserves identity\n'); fs.writeFileSync(path.join(destination,'保留.txt'),'existing target\n');
 const registry=new Registry({stateDir}); const root=registry.adoptRoot({rootPath:workspace,rootType:'project_workspace',contentPolicy:'bounded_content'});
 const from=registry.create({name:'原项目',currentPath:'原项目'}); const into=registry.create({name:'目标项目',currentPath:'目标项目'});
 for (const [project,relativePath] of [[from,'原项目'],[into,'目标项目']]) registry.attachRoot(project.project_id,{rootId:root.root_id,relativePath,reason:'Merge UI fixture'});
 const control=new ResourceControl({stateDir,registry}); const resource=control.identify({filePath:path.join(source,'说明.md'),project:registry.show(from.project_id).project});
 const intake=new Intake({stateDir}); const server=await startAtlasUiServer({stateDir,registry,intake,resourceControl:control,projectRoot:workspace,installationRoot:workspace});
 t.after(async()=>{await server.close();intake.dispose();control.dispose();registry.dispose();});
 const route=`/projects/${from.project_id}/membership`;
 const get=async url=>fetch(new URL(url,server.workspace_url));
 const post=async(url,form)=>fetch(new URL(url,server.workspace_url),{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(form),redirect:'manual'});
 const hidden=(html,name)=>{const match=html.match(new RegExp(`name="${name}" value="([^"]*)"`,'u'));assert.ok(match,`missing ${name}`);return match[1];};
 const first=await get(route); assert.equal(first.status,200); const html=await first.text();
 const prepared=await post(`${route}/prepare`,{csrf:hidden(html,'csrf'),operation:'merge',target_project_id:into.project_id,target_relative_path:'原项目材料',request_key:'merge-ui-preview'});
 assert.equal(prepared.status,303,await prepared.text()); const receipt=prepared.headers.get('location'); const preview=await(await get(receipt)).text();
 assert.equal(registry.show(from.project_id).project.status,'active'); assert.equal(fs.existsSync(path.join(destination,'原项目材料')),false);
 const execute=await post(`${receipt}/execute`,{csrf:hidden(preview,'csrf'),expected_revision:hidden(preview,'expected_revision'),expected_digest:hidden(preview,'expected_digest'),request_key:'merge-ui-confirm'});
 assert.equal(execute.status,303,await execute.text()); assert.equal(registry.show(from.project_id).project.status,'merged');
 const response=await get(receipt); assert.equal(response.status,200); const applied=await response.text(); assert.match(applied,/Files and membership changed/u);
 const read=await get(`/projects/${into.project_id}/resources/read?resource_id=${resource.resource_id}`); assert.equal(read.status,200); assert.match(await read.text(),/Merge preserves identity/u);
 assert.equal(fs.readFileSync(path.join(destination,'保留.txt'),'utf8'),'existing target\n');
 const undo=await post(`${receipt}/undo`,{csrf:hidden(applied,'csrf'),expected_revision:hidden(applied,'expected_revision'),expected_digest:hidden(applied,'expected_digest'),request_key:'merge-ui-undo'});
 assert.equal(undo.status,303,await undo.text()); assert.equal(registry.show(from.project_id).project.status,'active');
 assert.equal(fs.readFileSync(path.join(source,'说明.md'),'utf8'),'# Merge preserves identity\n'); assert.equal(fs.existsSync(path.join(destination,'原项目材料')),false);
 assert.match(await(await get(receipt)).text(),/Change undone/u);
});
