import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { Registry } from '../src/registry.js';
import { ResourceControl } from '../src/resource-control.js';
import { Intake } from '../src/intake.js';
import { startAtlasUiServer } from '../src/ui-server.js';

test('Reader opens local content without external launch and preserves scope, stale and cross-Project boundaries', async t => {
  const directory = fs.mkdtempSync(path.resolve('test/.tmp/reader-ui-'));
  const stateDir = path.join(directory, 'state');
  const workspace = path.join(directory, 'workspace');
  const source = path.join(workspace, '研究'); fs.mkdirSync(source, { recursive: true });
  const file = path.join(source, '阅读.md'); const original = '# Research\n\nA useful paragraph.\n\n[目标](目标.md#中文标题) [[研究/目标#中文标题|Wiki 目标]]\n\n<script>alert(1)</script>\n';
  fs.writeFileSync(file, original);
  const registry = new Registry({ stateDir });
  const root = registry.adoptRoot({ rootPath: workspace, rootType: 'project_workspace', contentPolicy: 'bounded_content' });
  const { project_id: id } = registry.create({ name: '研究', currentPath: '研究' });
  registry.attachRoot(id, { rootId: root.root_id, relativePath: '研究', reason: 'Reader fixture' });
  const control = new ResourceControl({ stateDir, registry });
  const resource = control.identify({ filePath: file, project: registry.show(id).project });
  const targetPath = path.join(source, '目标.md'); fs.writeFileSync(targetPath, '# 中文标题\n\nTarget reading.');
  const target = control.identify({ filePath: targetPath, project: registry.show(id).project });
  const candidate = { project_id: id, source_resource_id: resource.resource_id, target: { kind: 'resource', id: target.resource_id }, type: 'linked_to', evidence: { note: '已有中文关系 <evidence>' } };
  const preview = control.previewLinkedResource({ operation: 'add', candidate });
  control.submitLinkedResource({ operation: 'add', candidate, previewToken: preview.preview_token, requestKey: 'reader-ui-existing-link', caller: { tool: 'reader-test', client_run_id: 'reader-ui-chain' } });
  const intake = new Intake({ stateDir }); let externalOpens = 0;
  const server = await startAtlasUiServer({ stateDir, registry, intake, resourceControl: control,
    projectRoot: workspace, installationRoot: workspace, openLocalFileFn: async () => { externalOpens++; } });
  t.after(async () => { await server.close(); intake.dispose(); control.dispose(); registry.dispose(); });
  const base = `/projects/${id}/resources`;
  const returnTo = `${base}?mode=table&folder=notes&name_contains=useful`;
  const url = new URL(`${base}/read?resource_id=${resource.resource_id}&return_to=${encodeURIComponent(returnTo)}`, server.workspace_url);
  const response = await fetch(url); assert.equal(response.status, 200);
  const html = await response.text(); assert.match(html, /A useful paragraph/u);
  assert.doesNotMatch(html, /<script>alert\(1\)<\/script>/u);
  assert.ok(html.includes(returnTo.replaceAll('&', '&amp;')));
  assert.equal(externalOpens, 0); assert.equal(fs.readFileSync(file, 'utf8'), original);
  const targetHref = `/projects/${id}/resources/read?resource_id=${target.resource_id}#reader-heading-中文标题`;
  assert.ok(html.includes(`class="reader-material-link" href="${targetHref}"`));
  assert.match(html, /Stored relationships/u); assert.match(html, /已有中文关系 &lt;evidence&gt;/u);
  assert.match(html, /Related files have not been checked here/u);
  const targetResponse = await fetch(new URL(targetHref, server.workspace_url)); assert.equal(targetResponse.status, 200);
  const targetHtml = await targetResponse.text(); assert.match(targetHtml, /id="reader-heading-中文标题"/u); assert.match(targetHtml, /Target reading\./u);
  assert.match(targetHtml, /Incoming/u);
  const back = await fetch(url); assert.equal(back.status, 200); assert.match(await back.text(), /A useful paragraph/u);
  const detailResponse = await fetch(new URL(`${base}/detail?path=${encodeURIComponent('阅读.md')}&return_to=${encodeURIComponent(returnTo)}`, server.workspace_url));
  assert.equal(detailResponse.status, 200);
  assert.ok((await detailResponse.text()).includes(`href="${returnTo.replaceAll('&', '&amp;')}"`));
  const hash = (await import('node:crypto')).createHash('sha256').update(original).digest('hex');
  fs.writeFileSync(file, '# Changed\n'); url.searchParams.set('expected_sha256', hash);
  const stale = await fetch(url); assert.equal(stale.status, 409);
  assert.doesNotMatch(await stale.text(), /<h1[^>]*>Changed<\/h1>/u);
  url.searchParams.delete('expected_sha256'); url.searchParams.set('return_to', 'https://outside.invalid/');
  const safe = await (await fetch(url)).text(); assert.doesNotMatch(safe, /href="https:\/\/outside.invalid/u);
  const otherDir = path.join(workspace, '其他'); fs.mkdirSync(otherDir);
  const other = registry.create({ name: '其他', currentPath: '其他' });
  registry.attachRoot(other.project_id, { rootId: root.root_id, relativePath: '其他', reason: 'Other scope' });
  const outside = await fetch(new URL(`/projects/${other.project_id}/resources/read?resource_id=${resource.resource_id}`, server.workspace_url));
  assert.equal(outside.status, 409); assert.doesNotMatch(await outside.text(), /A useful paragraph/u);
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64');
  const imagePath = path.join(source, '示意.png'); fs.writeFileSync(imagePath, png);
  const imageResource = control.identify({ filePath: imagePath, project: registry.show(id).project });
  const imagePage = await fetch(new URL(`${base}/read?resource_id=${imageResource.resource_id}`, server.workspace_url));
  assert.equal(imagePage.status, 200);
  const imageHtml = await imagePage.text();
  const imageHash = (await import('node:crypto')).createHash('sha256').update(png).digest('hex');
  assert.ok(imageHtml.includes(`${base}/read-image?resource_id=${imageResource.resource_id}&amp;expected_sha256=${imageHash}`));
  assert.doesNotMatch(imageHtml, /src="data:/u);
  const imageUrl = new URL(`${base}/read-image?resource_id=${imageResource.resource_id}&expected_sha256=${imageHash}`, server.workspace_url);
  const imageResponse = await fetch(imageUrl);
  assert.equal(imageResponse.status, 200); assert.equal(imageResponse.headers.get('content-type'), 'image/png');
  assert.deepEqual(Buffer.from(await imageResponse.arrayBuffer()), png);
  fs.writeFileSync(imagePath, Buffer.concat([png, Buffer.from('changed')]));
  assert.equal((await fetch(imageUrl)).status, 409);
  assert.equal(externalOpens, 0);
});
