import assert from 'node:assert/strict';
import fs from 'node:fs'; import path from 'node:path'; import test from 'node:test';
import { ResourceControl, createResourceControl } from '../src/resource-control.js';
import { Registry } from '../src/registry.js';
const root=path.resolve('test','.tmp');
test('Resource Control keeps a logical ID across content changes and distinct paths', (t)=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-control-')); t.after(()=>fs.rmSync(dir,{recursive:true,force:true})); const stateDir=path.join(dir,'state'); const vault=path.join(dir,'vault'); fs.mkdirSync(path.join(vault,'Projects','Atlas'),{recursive:true}); const registry=new Registry({stateDir}); const project=registry.create({name:'Atlas',currentPath:'Projects/Atlas'}); registry.dispose(); const rc=createResourceControl({stateDir}); const one=path.join(vault,'Projects','Atlas','one.md'); const two=path.join(vault,'Projects','Atlas','two.md'); fs.writeFileSync(one,'same'); let first=rc.recordSave({saveId:'SAV-one',channel:'host',project:{id:project.project_id},target:{path:one},caller:{tool:'test'}}); assert.match(first.resource_id,/^RES-/u); fs.writeFileSync(one,'changed'); const again=rc.recordSave({saveId:'SAV-one',channel:'host',project:{id:project.project_id},target:{path:one},caller:{tool:'test'}}); assert.equal(again.resource_id,first.resource_id); fs.writeFileSync(two,'changed'); const other=rc.recordSave({saveId:'SAV-two',channel:'host',project:{id:project.project_id},target:{path:two},caller:{tool:'test'}}); assert.notEqual(other.resource_id,first.resource_id); assert.ok(first.relationships.some(r=>r.type==='stored_in')); rc.dispose();
});
test('Resource Control identifies active file locations without hash deduplication', (t)=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-identify-')); t.after(()=>fs.rmSync(dir,{recursive:true,force:true})); const stateDir=path.join(dir,'state'); const projectRoot=path.join(dir,'project'); fs.mkdirSync(projectRoot,{recursive:true}); const registry=new Registry({stateDir}); const project=registry.create({name:'Atlas',currentPath:'Projects/Atlas'}); registry.dispose(); const rc=createResourceControl({stateDir}); const one=path.join(projectRoot,'one.md'); const two=path.join(projectRoot,'two.md'); fs.writeFileSync(one,'same'); fs.writeFileSync(two,'same'); const first=rc.identify({filePath:one,project:{id:project.project_id}}); fs.writeFileSync(one,'changed'); const refreshed=rc.identify({filePath:one,project:{id:project.project_id}}); const separate=rc.identify({filePath:two,project:{id:project.project_id}}); assert.equal(refreshed.resource_id,first.resource_id); assert.equal(refreshed.external_change.status,'changed');assert.equal(rc.projectResources(project.project_id)[0].content_hash,first.evidence.sha256); assert.notEqual(separate.resource_id,first.resource_id); assert.equal(rc.projectResources(project.project_id).length,2); rc.dispose();
});

test('Observing a previously global Resource binds it to the Project without accepting a changed version',t=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-observe-project-bind-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const stateDir=path.join(dir,'state');const file=path.join(dir,'file.md');fs.writeFileSync(file,'one');const registry=new Registry({stateDir});const project=registry.create({name:'A',currentPath:'A'});const rc=createResourceControl({stateDir,ledger:registry.ledger});const global=rc.identify({filePath:file});fs.writeFileSync(file,'changed');const observed=rc.observe({filePath:file,project:{id:project.project_id}});assert.equal(observed.resource_id,global.resource_id);assert.equal(observed.locations.find(item=>item.status==='active').project_id,project.project_id);assert.equal(observed.external_change.status,'changed');assert.equal(observed.external_change.baseline.sha256,global.evidence.sha256);assert.notEqual(observed.external_change.current.sha256,global.evidence.sha256);rc.dispose();registry.dispose();
});

test('Resource Control rolls back a colliding path and preserves Import identity facts', (t)=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-control-collision-')); t.after(()=>fs.rmSync(dir,{recursive:true,force:true})); const stateDir=path.join(dir,'state'); const vault=path.join(dir,'vault'); fs.mkdirSync(path.join(vault,'Projects','Atlas'),{recursive:true}); const registry=new Registry({stateDir}); const project=registry.create({name:'Atlas',currentPath:'Projects/Atlas'}); registry.dispose(); const rc=createResourceControl({stateDir}); const file=path.join(vault,'Projects','Atlas','result.md'); fs.writeFileSync(file,'one'); const first=rc.recordSave({saveId:'SAV-one',channel:'host',project:{id:project.project_id},target:{path:file},caller:{tool:'test'}}); assert.throws(()=>rc.recordSave({saveId:'SAV-two',channel:'host',project:{id:project.project_id},target:{path:file},caller:{tool:'test'}}),/owns this path/u); assert.equal(rc.ledger.db.prepare('SELECT COUNT(*) AS count FROM resources').get().count,1); const imported=rc.recordSave({saveId:'SAV-import',channel:'import',project:{id:project.project_id},target:{path:file},source:{resource_id:first.resource_id},caller:{tool:'test'}}); assert.equal(imported.resource_id,first.resource_id); const relations=rc.ledger.resources.listRelationships(first.resource_id); assert.ok(relations.some(r=>r.type==='stored_in'&&r.target_kind==='project')); assert.ok(relations.some(r=>r.type==='used_by'&&r.target_kind==='project')); assert.equal(relations.some(r=>r.target_kind==='resource'&&r.target_id===r.source_resource_id),false); rc.dispose();
});

test('Resource relationships submit keeps explicit multi-Project facts and batch atomicity', (t)=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-relationships-')); t.after(()=>fs.rmSync(dir,{recursive:true,force:true})); const stateDir=path.join(dir,'state'); const external=path.join(dir,'external.md'); fs.writeFileSync(external,'external'); const registry=new Registry({stateDir}); const a=registry.create({name:'A',currentPath:'A'}); const b=registry.create({name:'B',currentPath:'B'}); const rc=createResourceControl({stateDir,ledger:registry.ledger}); const identified=rc.identify({filePath:external}); const caller={tool:'test',client_run_id:'relationship-run'}; const relations=rc.submitRelationships({caller,candidates:[{source_resource_id:identified.resource_id,target:{kind:'project',id:a.project_id},type:'used_by',evidence:{reason:'explicit'}},{source_resource_id:identified.resource_id,target:{kind:'project',id:b.project_id},type:'used_by',evidence:{reason:'explicit'}}]}); assert.equal(relations.length,2); assert.ok(relations.every(r=>r.submitter.caller.tool==='test'&&r.evidence.reason==='explicit'&&r.effective_at&&r.status==='active')); const duplicate=rc.submitRelationships({caller,candidates:[{source_resource_id:identified.resource_id,target:{kind:'project',id:a.project_id},type:'used_by',evidence:{reason:'explicit'}}]}); assert.equal(duplicate[0].id,relations[0].id); assert.throws(()=>rc.submitRelationships({caller,candidates:[{source_resource_id:identified.resource_id,target:{kind:'project',id:a.project_id},type:'used_by',evidence:{ok:true}},{source_resource_id:'RES-missing',target:{kind:'project',id:b.project_id},type:'used_by',evidence:{ok:true}}]}),/Candidate 1/u); assert.equal(rc.relationships(identified.resource_id).length,2); rc.dispose(); registry.dispose(); const reopened=createResourceControl({stateDir}); assert.equal(reopened.relationships(identified.resource_id).length,2); reopened.dispose();
});

test('Resource relationships enforce stored_in location and reject invalid batches without writes', (t)=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-relationship-gates-')); t.after(()=>fs.rmSync(dir,{recursive:true,force:true})); const stateDir=path.join(dir,'state'); const file=path.join(dir,'owned.md'); fs.writeFileSync(file,'owned'); const registry=new Registry({stateDir}); const a=registry.create({name:'A',currentPath:'A'}); const b=registry.create({name:'B',currentPath:'B'}); const rc=createResourceControl({stateDir,ledger:registry.ledger}); const id=rc.identify({filePath:file,project:{id:a.project_id}}).resource_id; const caller={tool:'test',client_run_id:'gates'}; assert.equal(rc.submitRelationships({caller,candidates:[{source_resource_id:id,target:{kind:'project',id:a.project_id},type:'stored_in',evidence:{location:'known'}}]}).length,1); assert.throws(()=>rc.submitRelationships({caller,candidates:[{source_resource_id:id,target:{kind:'project',id:b.project_id},type:'stored_in',evidence:{location:'wrong'}}]}),/Candidate 0/u); const count=()=>rc.relationships(id).length; for(const candidate of [{source_resource_id:'RES-none',target:{kind:'project',id:a.project_id},type:'used_by',evidence:{x:1}},{source_resource_id:id,target:{kind:'project',id:'PRJ-none'},type:'used_by',evidence:{x:1}},{source_resource_id:id,target:{kind:'project',id:a.project_id},type:'semantic',evidence:{x:1}},{source_resource_id:id,target:{kind:'project',id:a.project_id},type:'used_by',evidence:{}},{source_resource_id:id,target:{kind:'project',id:a.project_id},type:'used_by',evidence:'bad'}]){const before=count();assert.throws(()=>rc.submitRelationships({caller,candidates:[candidate]}),/Candidate 0/u);assert.equal(count(),before);} assert.throws(()=>rc.submitRelationships({caller:{client_run_id:'x'},candidates:[{source_resource_id:id,target:{kind:'project',id:a.project_id},type:'used_by',evidence:{x:1}}]}),/caller/u); assert.throws(()=>rc.submitRelationships({caller:{tool:'x'},candidates:[{source_resource_id:id,target:{kind:'project',id:a.project_id},type:'used_by',evidence:{x:1}}]}),/caller/u); rc.dispose(); registry.dispose();
});

test('Missing Resource refresh preserves its last location facts', (t)=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-missing-')); t.after(()=>fs.rmSync(dir,{recursive:true,force:true})); const stateDir=path.join(dir,'state'); const file=path.join(dir,'missing.md'); fs.writeFileSync(file,'last'); const registry=new Registry({stateDir}); const project=registry.create({name:'A',currentPath:'A'}); const rc=createResourceControl({stateDir,ledger:registry.ledger}); const identified=rc.identify({filePath:file,project:{id:project.project_id}}); fs.rmSync(file); const facts=rc.projectResources(project.project_id,{refresh:true}); assert.equal(facts[0].resource_status,'missing'); assert.equal(facts[0].status,'missing'); assert.equal(facts[0].path,file); assert.ok(facts[0].content_hash); rc.dispose(); registry.dispose(); const reopened=createResourceControl({stateDir}); assert.equal(reopened.projectResources(project.project_id)[0].resource_status,'missing'); reopened.dispose();
});

test('Missing one of a Resource locations preserves its active Resource state', (t)=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-partial-missing-')); t.after(()=>fs.rmSync(dir,{recursive:true,force:true})); const stateDir=path.join(dir,'state'); const a=path.join(dir,'a.md'); const b=path.join(dir,'b.md'); fs.writeFileSync(a,'same');fs.writeFileSync(b,'same');const registry=new Registry({stateDir});const project=registry.create({name:'A',currentPath:'A'});const rc=createResourceControl({stateDir,ledger:registry.ledger});const first=rc.identify({filePath:a,project:{id:project.project_id}}); rc.ledger.resources.ensureLocation({resourceId:first.resource_id,projectId:project.project_id,path:b,displayName:'b.md',evidence:{path:b,sha256:first.evidence.sha256,bytes:4,modified_at:new Date().toISOString()},at:new Date().toISOString()}); fs.rmSync(a);const facts=rc.projectResources(project.project_id,{refresh:true});assert.equal(facts[0].locations.find(x=>x.path===a).status,'missing');assert.equal(facts[0].resource_status,'active');rc.dispose();registry.dispose();
});

test('A Project can archive one missing location reminder while the same Resource stays active elsewhere', (t) => {
 const dir=fs.mkdtempSync(path.join(root,'resource-partial-archive-')); t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
 const stateDir=path.join(dir,'state'); const source=path.join(dir,'source.md'); const output=path.join(dir,'output.md'); fs.writeFileSync(source,'same'); fs.writeFileSync(output,'same');
 const registry=new Registry({stateDir}); const project=registry.create({name:'A',currentPath:'A'}); const rc=createResourceControl({stateDir,ledger:registry.ledger});
 const identified=rc.identify({filePath:source}); rc.ledger.resources.ensureLocation({resourceId:identified.resource_id,projectId:project.project_id,path:output,displayName:'output.md',evidence:{path:output,sha256:identified.evidence.sha256,bytes:4,modified_at:new Date().toISOString()},at:new Date().toISOString()});
 fs.rmSync(output); let fact=rc.projectResources(project.project_id,{refresh:true})[0]; assert.equal(fact.resource_status,'active'); assert.equal(fact.status,'missing');
 const caller={tool:'test',client_run_id:'partial-archive'}; const archived=rc.archiveMissingRecords({projectId:project.project_id,resourceIds:[identified.resource_id],caller}); assert.deepEqual(archived.archived,[identified.resource_id]);
 fact=rc.projectResources(project.project_id)[0]; assert.equal(fact.missing_record_archived,true); assert.equal(fact.resource_status,'active'); assert.equal(fs.readFileSync(source,'utf8'),'same');
 rc.restoreMissingRecords({projectId:project.project_id,resourceIds:[identified.resource_id],caller}); assert.equal(rc.projectResources(project.project_id)[0].missing_record_archived,false);
 rc.dispose(); registry.dispose();
});

test('Project Resource facts distinguish external Used by from Stored in', (t)=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-project-facts-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const stateDir=path.join(dir,'state');const ext=path.join(dir,'ext.md');const inside=path.join(dir,'inside.md');fs.writeFileSync(ext,'x');fs.writeFileSync(inside,'y');const registry=new Registry({stateDir});const a=registry.create({name:'A',currentPath:'A'});const b=registry.create({name:'B',currentPath:'B'});const rc=createResourceControl({stateDir,ledger:registry.ledger});const external=rc.identify({filePath:ext});const stored=rc.identify({filePath:inside,project:{id:a.project_id}});rc.submitRelationships({caller:{tool:'test',client_run_id:'facts'},candidates:[{source_resource_id:external.resource_id,target:{kind:'project',id:a.project_id},type:'used_by',evidence:{reason:'explicit'}},{source_resource_id:external.resource_id,target:{kind:'project',id:b.project_id},type:'used_by',evidence:{reason:'explicit'}}]});assert.equal(rc.projectResources(a.project_id).find(x=>x.resource_id===external.resource_id).relationship_label,'Used by');assert.equal(rc.projectResources(b.project_id).find(x=>x.resource_id===external.resource_id).relationship_label,'Used by');assert.equal(rc.projectResources(a.project_id).find(x=>x.resource_id===stored.resource_id).relationship_label,'Stored in');rc.dispose();registry.dispose();
});

test('Missing Resource refresh refuses a linked ancestor without changing facts', (t)=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-link-refresh-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true,maxRetries:5,retryDelay:20}));const stateDir=path.join(dir,'state');const parent=path.join(dir,'parent');const backup=path.join(dir,'backup');const file=path.join(parent,'file.md');fs.mkdirSync(parent);fs.writeFileSync(file,'safe');const registry=new Registry({stateDir});const project=registry.create({name:'A',currentPath:'A'});const rc=createResourceControl({stateDir,ledger:registry.ledger});const identified=rc.identify({filePath:file,project:{id:project.project_id}});const before=rc.projectResources(project.project_id)[0];fs.renameSync(parent,backup);try{fs.symlinkSync(backup,parent,'junction');}catch(error){t.skip(`Junction creation is unavailable: ${error.code??error.message}`);return;}assert.throws(()=>rc.projectResources(project.project_id,{refresh:true}));const after=rc.projectResources(project.project_id)[0];assert.equal(after.status,'active');assert.equal(after.resource_status,'active');assert.equal(after.content_hash,before.content_hash);rc.dispose();registry.dispose();const reopened=createResourceControl({stateDir});assert.equal(reopened.projectResources(project.project_id)[0].status,'active');reopened.dispose();
});

test('Project Resource check preserves its baseline until the user accepts the external change', (t)=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-refresh-evidence-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const stateDir=path.join(dir,'state');const file=path.join(dir,'file.md');fs.writeFileSync(file,'one');const registry=new Registry({stateDir});const project=registry.create({name:'A',currentPath:'A'});const rc=createResourceControl({stateDir,ledger:registry.ledger});const first=rc.identify({filePath:file,project:{id:project.project_id}});let checked=rc.projectResources(project.project_id,{refresh:true})[0];assert.equal(checked.external_change.status,'unchanged');assert.equal(checked.external_change.baseline.sha256,first.evidence.sha256);fs.writeFileSync(file,'changed content');checked=rc.projectResources(project.project_id,{refresh:true})[0];assert.equal(checked.resource_id,first.resource_id);assert.equal(checked.content_hash,first.evidence.sha256);assert.notEqual(checked.external_change.current.sha256,first.evidence.sha256);assert.equal(checked.external_change.current.bytes,15);assert.equal(checked.external_change.status,'changed');rc.dispose();registry.dispose();const reopened=createResourceControl({stateDir});const persisted=reopened.projectResources(project.project_id,{refresh:true})[0];assert.equal(persisted.external_change.status,'changed');const accepted=reopened.acceptCurrentVersion({projectId:project.project_id,resourceId:first.resource_id,expectedCurrentVersion:persisted.external_change.current.sha256,caller:{tool:'test',client_run_id:'accept-current'}});assert.equal(accepted.external_change.status,'unchanged');assert.equal(accepted.content_hash,persisted.external_change.current.sha256);reopened.dispose();
});

test('Project scoped refresh ignores an unrelated linked ancestor', (t)=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-refresh-scope-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true,maxRetries:5,retryDelay:20}));const stateDir=path.join(dir,'state');const aFile=path.join(dir,'a.md');const bParent=path.join(dir,'b');const bBackup=path.join(dir,'b-backup');const bFile=path.join(bParent,'b.md');fs.writeFileSync(aFile,'a');fs.mkdirSync(bParent);fs.writeFileSync(bFile,'b');const registry=new Registry({stateDir});const a=registry.create({name:'A',currentPath:'A'});const b=registry.create({name:'B',currentPath:'B'});const rc=createResourceControl({stateDir,ledger:registry.ledger});rc.identify({filePath:aFile,project:{id:a.project_id}});rc.identify({filePath:bFile,project:{id:b.project_id}});fs.renameSync(bParent,bBackup);try{fs.symlinkSync(bBackup,bParent,'junction');}catch(error){t.skip(`Junction creation is unavailable: ${error.code??error.message}`);return;}fs.writeFileSync(aFile,'updated');const facts=rc.projectResources(a.project_id,{refresh:true});assert.equal(facts[0].bytes,1);assert.equal(facts[0].external_change.current.bytes,7);assert.equal(facts[0].external_change.status,'changed');assert.equal(rc.projectResources(b.project_id)[0].status,'active');rc.dispose();registry.dispose();
});

test('Resource actions preserve missing records and distinguish relationship removal facts', (t)=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-actions-')); const stateDir=path.join(dir,'state'); const missingFile=path.join(dir,'missing.md'); const activeFile=path.join(dir,'active.md'); fs.writeFileSync(missingFile,'missing evidence');fs.writeFileSync(activeFile,'active evidence'); const registry=new Registry({stateDir});const project=registry.create({name:'A',currentPath:'A'});const rc=createResourceControl({stateDir,ledger:registry.ledger});t.after(()=>{rc.dispose();registry.dispose();fs.rmSync(dir,{recursive:true,force:true,maxRetries:5,retryDelay:20});});
 const caller={tool:'test',client_run_id:'resource-actions'};
 const missing=rc.identify({filePath:missingFile,project:{id:project.project_id}});fs.rmSync(missingFile);rc.projectResources(project.project_id,{refresh:true});
 const kept=rc.keepRecord(missing.resource_id,{caller});assert.equal(kept.action_type,'keep_record');assert.equal(kept.status,'completed');assert.equal(rc.describe(missing.resource_id).resource.status,'missing');assert.equal(fs.existsSync(missingFile),false);
 const active=rc.identify({filePath:activeFile,project:{id:project.project_id}});const [used]=rc.submitRelationships({caller,candidates:[{source_resource_id:active.resource_id,target:{kind:'project',id:project.project_id},type:'used_by',evidence:{reason:'explicit'}}]});const [stored]=rc.submitRelationships({caller,candidates:[{source_resource_id:active.resource_id,target:{kind:'project',id:project.project_id},type:'stored_in',evidence:{location:'known'}}]});const hash=active.evidence.sha256;
 const forgotten=rc.forgetRelationship(stored.id,{caller});assert.equal(forgotten.action_type,'forget_relationship');assert.equal(rc.ledger.resources.relationshipById(stored.id).status,'forgotten');assert.throws(()=>rc.forgetRelationship(stored.id,{caller}),/unavailable/u);const removed=rc.removeReference(used.id,{caller});assert.equal(removed.action_type,'remove_reference');assert.equal(rc.ledger.resources.relationshipById(used.id).status,'removed');assert.throws(()=>rc.removeReference(used.id,{caller}),/active Used by/u);assert.equal(rc.describe(active.resource_id).actions.filter(a=>a.action_type==='forget_relationship').length,1);assert.equal(rc.describe(active.resource_id).actions.filter(a=>a.action_type==='remove_reference').length,1);assert.equal(fs.existsSync(activeFile),true);assert.equal(rc.identify({filePath:activeFile,project:{id:project.project_id}}).evidence.sha256,hash);
 assert.throws(()=>rc.removeReference(stored.id,{caller}),/active Used by/u);assert.throws(()=>rc.forgetRelationship(used.id,{caller}),/unavailable/u);assert.throws(()=>rc.keepRecord(active.resource_id,{caller}),/missing/u);assert.throws(()=>rc.keepRecord(missing.resource_id,{caller:{tool:'test'}}),/caller/u);assert.throws(()=>rc.describe('RES-unknown'),/unavailable/u);assert.equal(typeof ResourceControl.prototype.delete,'undefined');assert.equal(typeof ResourceControl.prototype.deleteFile,'undefined');
 const described=rc.describe(active.resource_id);assert.deepEqual(described.actions.map(item=>item.action_type).sort(),['forget_relationship','remove_reference']);
});

test('Resource action failures leave relationships and actions unchanged', (t)=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-action-invalid-'));const stateDir=path.join(dir,'state');const file=path.join(dir,'file.md');fs.writeFileSync(file,'content');const registry=new Registry({stateDir});const project=registry.create({name:'A',currentPath:'A'});const rc=createResourceControl({stateDir,ledger:registry.ledger});t.after(()=>{rc.dispose();registry.dispose();fs.rmSync(dir,{recursive:true,force:true,maxRetries:5,retryDelay:20});});
 const resource=rc.identify({filePath:file,project:{id:project.project_id}});const caller={tool:'test',client_run_id:'invalid-actions'};const [stored]=rc.submitRelationships({caller,candidates:[{source_resource_id:resource.resource_id,target:{kind:'project',id:project.project_id},type:'stored_in',evidence:{location:'known'}}]});const before=rc.describe(resource.resource_id);
 assert.throws(()=>rc.removeReference(stored.id,{caller}),/Used by/u);assert.throws(()=>rc.forgetRelationship('REL-missing',{caller}),/unavailable/u);assert.throws(()=>rc.forgetRelationship(stored.id,{caller:{client_run_id:'missing-tool'}}),/caller/u);const after=rc.describe(resource.resource_id);assert.equal(after.relationships.find(item=>item.id===stored.id).status,'active');assert.equal(after.actions.length,before.actions.length);assert.equal(fs.readFileSync(file,'utf8'),'content');
});

test('Resource relink preserves a missing RES and its Project location facts across restart', (t)=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-relink-'));const stateDir=path.join(dir,'state');const oldFile=path.join(dir,'old.md');const newFile=path.join(dir,'replacement.md');fs.writeFileSync(oldFile,'original');fs.writeFileSync(newFile,'replacement');const registry=new Registry({stateDir});const project=registry.create({name:'A',currentPath:'A'});const rc=createResourceControl({stateDir,ledger:registry.ledger});t.after(()=>{rc.dispose();registry.dispose();fs.rmSync(dir,{recursive:true,force:true,maxRetries:5,retryDelay:20});});
 const original=rc.identify({filePath:oldFile,project:{id:project.project_id}});fs.rmSync(oldFile);rc.projectResources(project.project_id,{refresh:true});const relinked=rc.relink({resourceId:original.resource_id,filePath:newFile,caller:{tool:'test',client_run_id:'relink'}});assert.equal(relinked.resource_id,original.resource_id);assert.equal(fs.readFileSync(newFile,'utf8'),'replacement');const detail=rc.describe(original.resource_id);assert.equal(detail.resource.status,'active');assert.equal(detail.locations.filter(item=>item.status==='missing').length,1);const active=detail.locations.find(item=>item.status==='active');assert.equal(active.path,path.resolve(newFile));assert.equal(active.project_id,project.project_id);assert.equal(active.content_hash,relinked.evidence.sha256);assert.equal(detail.actions.at(-1).action_type,'relink');assert.equal(detail.actions.at(-1).details.old_location.status,'missing');assert.equal(detail.actions.at(-1).details.new_location.path,path.resolve(newFile));
 registry.dispose();const reopened=createResourceControl({stateDir});const after=reopened.describe(original.resource_id);assert.equal(after.resource.status,'active');assert.equal(after.locations.find(item=>item.status==='active').path,path.resolve(newFile));assert.equal(after.actions.at(-1).action_type,'relink');reopened.dispose();
});

test('Resource relink rejects collisions, active resources, invalid callers, and linked paths without facts', (t)=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-relink-reject-'));const stateDir=path.join(dir,'state');const oldFile=path.join(dir,'old.md');const owned=path.join(dir,'owned.md');const another=path.join(dir,'another.md');const linkedTarget=path.join(dir,'linked-target');const linkedParent=path.join(dir,'linked-parent');fs.writeFileSync(oldFile,'old');fs.writeFileSync(owned,'owned');fs.writeFileSync(another,'another');fs.mkdirSync(linkedTarget);fs.writeFileSync(path.join(linkedTarget,'candidate.md'),'candidate');const registry=new Registry({stateDir});const project=registry.create({name:'A',currentPath:'A'});const rc=createResourceControl({stateDir,ledger:registry.ledger});t.after(()=>{rc.dispose();registry.dispose();fs.rmSync(dir,{recursive:true,force:true,maxRetries:5,retryDelay:20});});
 const missing=rc.identify({filePath:oldFile,project:{id:project.project_id}});const active=rc.identify({filePath:owned,project:{id:project.project_id}});fs.rmSync(oldFile);rc.projectResources(project.project_id,{refresh:true});const caller={tool:'test',client_run_id:'relink-reject'};const before=rc.describe(missing.resource_id);
 assert.throws(()=>rc.relink({resourceId:missing.resource_id,filePath:owned,caller}),/owns this path/u);assert.throws(()=>rc.relink({resourceId:active.resource_id,filePath:another,caller}),/missing Resource/u);assert.throws(()=>rc.relink({resourceId:missing.resource_id,filePath:owned,caller:{tool:'test'}}),/caller/u);assert.throws(()=>rc.relink({resourceId:'RES-none',filePath:owned,caller}),/unavailable/u);assert.equal(rc.describe(missing.resource_id).locations.length,before.locations.length);assert.equal(rc.describe(missing.resource_id).actions.length,before.actions.length);
 try{fs.symlinkSync(linkedTarget,linkedParent,'junction');}catch(error){t.skip(`Junction creation is unavailable: ${error.code??error.message}`);return;}assert.throws(()=>rc.relink({resourceId:missing.resource_id,filePath:path.join(linkedParent,'candidate.md'),caller}),/symbolic link|junction/u);const unchanged=rc.describe(missing.resource_id);assert.equal(unchanged.resource.status,'missing');assert.equal(unchanged.actions.length,before.actions.length);assert.equal(typeof ResourceControl.prototype.delete,'undefined');
});

test('Resource location ownership survives refresh for another Project', (t)=>{
 const dir=fs.mkdtempSync(path.join(root,'resource-location-ownership-'));const stateDir=path.join(dir,'state');const file=path.join(dir,'file.md');fs.writeFileSync(file,'one');const registry=new Registry({stateDir});const a=registry.create({name:'A',currentPath:'A'});const b=registry.create({name:'B',currentPath:'B'});const rc=createResourceControl({stateDir,ledger:registry.ledger});t.after(()=>{rc.dispose();registry.dispose();fs.rmSync(dir,{recursive:true,force:true,maxRetries:5,retryDelay:20});});const identified=rc.identify({filePath:file,project:{id:a.project_id}});fs.writeFileSync(file,'two changed');const facts=rc.identify({filePath:file,project:{id:a.project_id}}).evidence;const refreshed=rc.ledger.resources.ensureLocation({resourceId:identified.resource_id,projectId:b.project_id,path:file,displayName:'file.md',evidence:facts,at:new Date().toISOString()});assert.equal(refreshed.project_id,a.project_id);assert.equal(refreshed.content_hash,facts.sha256);const persisted=rc.ledger.resources.locations(identified.resource_id)[0];assert.equal(persisted.project_id,a.project_id);assert.equal(persisted.bytes,facts.bytes);const nullRefresh=rc.ledger.resources.ensureLocation({resourceId:identified.resource_id,projectId:null,path:file,displayName:'file.md',evidence:facts,at:new Date().toISOString()});assert.equal(nullRefresh.project_id,a.project_id);
});
