import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { Registry } from '../src/registry.js';
import { createResourceControl } from '../src/resource-control.js';
import { createSaveService } from '../src/save-service.js';
import { createDataWorkService } from '../src/ui/services/data-work-service.js';
import { createModuleAvailabilityService } from '../src/module-availability.js';
import { startAtlasUiServer } from '../src/ui-server.js';
const decode=v=>v.replaceAll('&amp;','&').replaceAll('&quot;','"').replaceAll('&#39;',"'").replaceAll('&lt;','<').replaceAll('&gt;','>');
function selectedOption(html,name) {
 const select=html.match(new RegExp('<select\\b[^>]*name="'+name+'"[^>]*>([\\s\\S]*?)<\\/select>','u'));
 assert.ok(select, 'Expected named field '+name);
 const option=select[1].match(/<option\b(?=[^>]*\bselected(?:\s|>))[^>]*\bvalue="([^"]*)"[^>]*>/u);
 return option ? decode(option[1]) : null;
}
function formFields(html,match){const form=[...html.matchAll(/<form\b([^>]*)>([\s\S]*?)<\/form>/gu)].find(m=>m[1].includes(match)||m[2].includes('name="action" value="'+match+'"'));assert.ok(form,match);const values=new URLSearchParams();for(const m of form[2].matchAll(/<input[^>]*name="([^"]+)"[^>]*value="([^"]*)"[^>]*>/gu)){if(/type="(?:checkbox|radio)"/u.test(m[0]) && !/\bchecked\b/u.test(m[0]))continue;values.append(m[1],decode(m[2]));}return values;}
async function fixture(t,content='group,amount\nNorth,oops\nSouth,10\n'){
 const root=fs.mkdtempSync(path.resolve('test/.tmp/toolbox-pipelines-')),stateDir=path.join(root,'state'),workspace=path.join(root,'workspace');fs.mkdirSync(workspace);
 const registry=new Registry({stateDir});const adopted=registry.adoptRoot({rootPath:workspace,rootType:'project_workspace',contentPolicy:'structure_only'});
 const projects=['A','B'].map(folder=>{fs.mkdirSync(path.join(workspace,folder,'Sources'),{recursive:true});const p=registry.create({name:folder,currentPath:folder});registry.attachRoot(p.project_id,{rootId:adopted.root_id,relativePath:folder,reason:'Toolbox pipeline fixture'});return registry.show(p.project_id).project;});
 const control=createResourceControl({stateDir,ledger:registry.ledger}),save=createSaveService({stateDir,resourceControl:control});const file=path.join(workspace,'A','input.csv');fs.writeFileSync(file,content);const resource=control.identify({filePath:file,project:projects[0]}).resource_id;
 const foreignFile=path.join(workspace,'B','other.csv');fs.writeFileSync(foreignFile,'x\n1\n');const foreign=control.identify({filePath:foreignFile,project:projects[1]}).resource_id;
 const dataWork=createDataWorkService({stateDir,projectRoot:path.resolve('.'),installationRoot:path.resolve('.'),resourceControl:control});let fetches=0;
 const server=await startAtlasUiServer({stateDir,registry,intake:save.intake,resourceControl:control,dataWorkService:dataWork,projectRoot:path.resolve('.'),installationRoot:path.resolve('.'),captureSourceOptions:{saveService:save,lookupHost:async()=>[{address:'93.184.216.34',family:4}],fetchImpl:async(url)=>{fetches++;if(String(url).includes('/network'))throw Error('network fetch failed');if(String(url).includes('/expired'))return new Response('Sign in',{status:403,headers:{'content-type':'text/html'}});return new Response('<html><title>Public article</title><script>unsafe()</script><article><p>Actual readable public content.</p></article></html>',{headers:{'content-type':'text/html; charset=utf-8'}});}}});
 t.after(async()=>{await server.close();save.dispose();control.dispose();registry.dispose();fs.rmSync(root,{recursive:true,force:true,maxRetries:5,retryDelay:20});});
 const base='/projects/'+projects[0].id,toolbox='/toolbox?project_id='+projects[0].id;
 const get=async(route)=>{const response=await fetch(new URL(route,server.workspace_url));return {status:response.status,html:await response.text()};};const post=(route,values)=>fetch(new URL(route,server.workspace_url),{method:'POST',redirect:'manual',body:new URLSearchParams(values)});
 return {root,stateDir,workspace,registry,projects,control,save,dataWork,file,resource,foreign,base,toolbox,get,post,fetches:()=>fetches};
}
test('Toolbox public Markdown previews actual md, confirms ordinary Save, preserves exit and replays without refetch', {timeout:30000},async t=>{
 const f=await fixture(t);const page=await f.get(f.toolbox);assert.equal(page.status,200);assert.match(page.html,/Content conversion/u);assert.match(page.html,/static public HTML/u);const params=formFields(page.html,'/toolbox/markdown');params.set('url','https://example.test/article');params.set('folder','Sources');params.set('name','article.md');
 let response=await f.post(f.base+'/toolbox/markdown?project_id='+f.projects[1].id,params);assert.equal(response.status,303);const saveHref=response.headers.get('location'),target=path.join(f.workspace,'A','Sources','article.md');assert.equal(fs.existsSync(target),false);assert.equal(f.fetches(),1);
 const preview=await f.get(saveHref);assert.equal(preview.status,200);assert.match(preview.html,/Actual readable public content/u);assert.doesNotMatch(preview.html,/atlas.source-capture.v1|unsafe\(\)/u);assert.ok(preview.html.includes(f.toolbox.replaceAll('&','&amp;')));assert.equal(fs.existsSync(target),false);
 response=await f.post(f.base+'/toolbox/markdown',params);assert.equal(response.headers.get('location'),saveHref);assert.equal(f.fetches(),1);
 const wrongReturn=await f.get(new URL(saveHref,'http://local').pathname+'?return_to='+encodeURIComponent('/toolbox?project_id='+f.projects[1].id));assert.equal(formFields(wrongReturn.html,'/execute').has('return_to'),false);const execute=formFields(preview.html,'/execute');const stale=new URLSearchParams(execute);stale.set('preview_revision','0'.repeat(64));response=await f.post(new URL(saveHref,'http://local').pathname+'/execute',stale);assert.equal(response.status,409);assert.equal(fs.existsSync(target),false);response=await f.post(new URL(saveHref,'http://local').pathname+'/execute',execute);assert.equal(response.status,303);assert.match(fs.readFileSync(target,'utf8'),/# Public article/u);assert.match(fs.readFileSync(target,'utf8'),/Actual readable public content/u);
 const saved=await f.get(response.headers.get('location'));assert.ok(saved.html.includes(f.toolbox));const receipt=f.save.findByRequestKey({channel:'host',requestKey:params.get('request_key'),caller:{tool:'atlas-ui',client_run_id:'toolbox-markdown:'+f.projects[0].id}});assert.equal(receipt.source.kind,'public_markdown');assert.equal(receipt.project.id,f.projects[0].id);assert.ok(receipt.resource_id);
 const read=await f.get(f.base+'/resources/read?resource_id='+receipt.resource_id);assert.equal(read.status,200);assert.match(read.html,/Actual readable public content/u);
 response=await f.post(new URL(saveHref,'http://local').pathname+'/undo',formFields(saved.html,'/undo'));assert.equal(response.status,303);assert.equal(fs.existsSync(target),false);response=await f.post(f.base+'/toolbox/markdown',params);assert.equal(response.status,303);assert.equal(f.fetches(),1);assert.equal(fs.existsSync(target),false);
});
test('Toolbox interrupted Markdown reservation stays explicit and retains inputs without a Project-less Save redirect', {timeout:30000},async t=>{
 const f=await fixture(t),page=await f.get(f.toolbox),params=formFields(page.html,'/toolbox/markdown');
 params.set('url','https://example.test/article');params.set('folder','Sources');params.set('name','pending.md');
 const writeJournal=f.save.writeJournal;f.save.writeJournal=(state,items)=>{writeJournal(state,items);if(items.some(row=>row.status==='reserving'))throw Error('Fixture interruption after reservation journal');};
 let response=await f.post(f.base+'/toolbox/markdown',params);assert.equal(response.status,409);assert.equal(response.headers.get('location'),null);
 let html=await response.text();assert.match(html,/no confirmable preview yet/u);assert.match(html,/reserving/u);assert.ok(html.includes(params.get('request_key')));assert.match(html,/value="pending.md"/u);
 response=await f.post(f.base+'/toolbox/markdown',params);assert.equal(response.status,409);assert.equal(f.fetches(),1);
 assert.equal(fs.existsSync(path.join(f.workspace,'A','Sources','pending.md')),false);
});

test('Markdown errors retain escaped inputs/key with supported fallback, CSRF and module/Project guards', {timeout:30000},async t=>{
 const f=await fixture(t);const page=await f.get(f.toolbox),params=formFields(page.html,'/toolbox/markdown');params.set('url','https://example.test/article');params.set('folder','missing');params.set('name','draft');
 let response=await f.post(f.base+'/toolbox/markdown',params);assert.equal(response.status,409);let html=await response.text();assert.match(html,/Choose an existing folder/u);assert.match(html,/value="missing" selected/u);assert.match(html,/value="draft"/u);assert.ok(html.includes(params.get('request_key')));assert.equal(f.fetches(),0);
 params.set('folder','Sources');params.set('name','<script>bad</script>');response=await f.post(f.base+'/toolbox/markdown',params);assert.equal(response.status,409);html=await response.text();assert.match(html,/&lt;script&gt;bad&lt;\/script&gt;/u);assert.doesNotMatch(html,/<script>bad/u);assert.equal(f.fetches(),0);
 params.set('name','network');params.set('url','https://example.test/network');response=await f.post(f.base+'/toolbox/markdown',params);assert.equal(response.status,409);html=await response.text();assert.match(html,/could not be fetched/u);assert.match(html,/value="https:\/\/example.test\/network"/u);assert.match(html,/Capture source \/ import/u);
 params.set('url','https://chatgpt.com/share/expired');params.set('name','export');response=await f.post(f.base+'/toolbox/markdown',params);assert.equal(response.status,422);assert.match(await response.text(),/requires an export/u);
 const count=f.fetches();params.set('url','http://127.0.0.1/private');params.set('name','private');response=await f.post(f.base+'/toolbox/markdown',params);assert.equal(response.status,409);assert.equal(f.fetches(),count);
 params.set('csrf','wrong');response=await f.post(f.base+'/toolbox/markdown',params);assert.equal(response.status,403);params.set('csrf',formFields(page.html,'/toolbox/markdown').get('csrf'));
 const modules=createModuleAvailabilityService({stateDir:f.stateDir}),module=modules.get('atlas.capture-source');modules.change({moduleId:module.module_id,enabled:false,expectedRevision:module.revision,requestKey:'pause-content',reason:'Fixture'});params.set('url','https://example.test/article');response=await f.post(f.base+'/toolbox/markdown',params);assert.equal(response.status,409);assert.match(await response.text(),/Content conversion is unavailable/u);assert.equal(f.fetches(),count);
 assert.deepEqual(fs.readdirSync(path.join(f.workspace,'A','Sources')),[]);
});
test('Table input recovery retains trusted selection/tool and exact-revision draft; real numeric-data refusal creates no Save', {timeout:30000},async t=>{
 const f=await fixture(t),original=fs.readFileSync(f.file),page=await f.get(f.toolbox),params=formFields(page.html,'/toolbox/start');params.set('tool','aggregate');let response=await f.post(f.base+'/toolbox/start',params);assert.equal(response.status,303);let failed=await f.get(response.headers.get('location'));assert.match(failed.html,/Choose at least one CSV or XLSX/u);assert.match(failed.html,/name="tool" value="aggregate" checked/u);
 params.append('resource_ids',f.resource);params.append('resource_ids',f.foreign);response=await f.post(f.base+'/toolbox/start',params);failed=await f.get(response.headers.get('location'));assert.match(failed.html,new RegExp('value="'+f.resource+'" checked','u'));assert.doesNotMatch(failed.html,new RegExp('value="'+f.foreign+'"','u'));
 params.delete('resource_ids');params.set('resource_ids',f.resource);response=await f.post(f.base+'/toolbox/start',params);const review=await f.get(response.headers.get('location'));assert.ok(review.html.includes(f.toolbox));const commit=formFields(review.html,'/work/commit');commit.set('target','new');response=await f.post(f.base+'/work/commit',commit);const workHref=response.headers.get('location'),workId=workHref.split('/').at(-1);let work=await f.get(workHref);assert.match(work.html,/Leave this Work available/u);response=await f.post(workHref+'/action',formFields(work.html,'prepare_sources'));work=await f.get(workHref);response=await f.post(workHref+'/action',formFields(work.html,'confirm_mapping'));work=await f.get(workHref);
 const before=f.dataWork.session(workId),csrf=params.get('csrf'),recipe=new URLSearchParams({csrf,action:'recipe',base_revision:String(before.revision),combine:'concatenate',aggregate_dimension:'group',aggregate_measure:'amount',aggregate_formula:'sum',aggregate_unit:'',aggregate_null_policy:'exclude',rename_column:'',rename_to:'draft <name>'});response=await f.post(workHref+'/action',recipe);assert.equal(response.status,303);failed=await f.get(workHref);assert.match(failed.html,/unit label/u);assert.match(failed.html,/name="aggregate_unit"[^>]*value=""/u);assert.equal(selectedOption(failed.html,'aggregate_measure'),'amount');assert.match(failed.html,/draft &lt;name&gt;/u);assert.equal(f.dataWork.session(workId).revision,before.revision);assert.deepEqual(fs.readFileSync(f.file),original);
 recipe.set('aggregate_unit','items');recipe.set('rename_to','');response=await f.post(workHref+'/action',recipe);assert.equal(response.status,303);const valid=f.dataWork.session(workId);assert.ok(valid.revision>before.revision);response=await f.post(workHref+'/action',{csrf,action:'preview',base_revision:String(valid.revision)});assert.equal(response.status,303);failed=await f.get(workHref);assert.match(failed.html,/nonnumeric or nonfinite/u);assert.equal(f.dataWork.session(workId).preview,null);assert.equal(f.dataWork.session(workId).latest_save_id,null);assert.match(failed.html,/name="aggregate_unit"[^>]*value="items"/u);assert.deepEqual(fs.readFileSync(f.file),original);
 recipe.set('aggregate_unit','old-draft');response=await f.post(workHref+'/action',recipe);assert.match(response.headers.get('location'),/draft_conflict=/u);const conflicted=await f.get(response.headers.get('location'));assert.match(conflicted.html,/draft/u);assert.equal(f.dataWork.session(workId).revision,valid.revision);assert.match(conflicted.html,/name="aggregate_unit"[^>]*value="items"/u);assert.doesNotMatch(conflicted.html,/name="aggregate_unit"[^>]*value="old-draft"/u);
 response=await f.post(workHref+'/action',{csrf:'wrong',action:'recipe',base_revision:valid.revision});assert.ok(response.status>=400);assert.equal(f.dataWork.session(workId).revision,valid.revision);
});
