import { UI_DISPLAY_NAME } from '../brand.js';
import { escapeHtml as h, renderNav, renderTopbar, renderUiClientScript } from '../components.js';
import { uiStyles } from '../styles.js';
import { normalizeUiLocale, translateUi } from '../i18n.js';
export function renderToolboxView(model, options = {}) {
 const t=key=>translateUi(options.locale,'toolbox.'+key,options.languageCatalog),base=model.project ? '/projects/'+encodeURIComponent(model.project.id):null;
 const tools=['pipeline','aggregate','pivot','trend'], selected=model.selected_ids ?? [], tool=model.tool ?? 'pipeline',draft=model.markdown ?? {};
 const moduleLink='<a href="/modules?project_id='+encodeURIComponent(model.project?.id ?? '')+'">'+h(translateUi(options.locale,'modules.open',options.languageCatalog))+'</a>';
 const purpose=key=>'<span><strong>'+h(t(key))+'</strong><small>'+h(t(key+'_help'))+'</small></span>';
 const table=!base ? '<p>'+h(t('choose'))+'</p><ul>'+model.projects.map(p=>'<li><a href="/toolbox?project_id='+encodeURIComponent(p.id)+'">'+h(p.name)+'</a></li>').join('')+'</ul><div class="toolbox-tools">'+tools.map(key=>'<span aria-disabled="true">'+purpose(key)+'</span>').join('')+'</div>' : model.paused ? '<p class="callout warn">'+h(t('paused'))+' '+moduleLink+'</p>' : model.resources.length ? '<form method="post" action="'+base+'/toolbox/start"><input type="hidden" name="csrf" value="'+h(options.csrfToken)+'"><fieldset><legend>'+h(t('materials'))+'</legend><div class="toolbox-materials">'+model.resources.map(r=>'<label><input type="checkbox" name="resource_ids" value="'+h(r.resource_id)+'"'+(selected.includes(r.resource_id)?' checked':'')+'> <strong>'+h(r.name)+'</strong><small>'+h(r.relative_path)+'</small></label>').join('')+'</div></fieldset><fieldset><legend>'+h(t('table_category'))+'</legend><div class="toolbox-tools">'+tools.map(key=>'<label><input type="radio" name="tool" value="'+key+'"'+(tool===key?' checked':'')+'> '+purpose(key)+'</label>').join('')+'</div></fieldset><p class="muted">'+h(t('hint'))+'</p><button class="action-button">'+h(t('start'))+'</button></form>' : '<p>'+h(t('empty'))+'</p>';
 const folders=(model.folders ?? []).map(folder=>typeof folder==='string'?folder:folder.relative_path ?? folder.path ?? '.');
 const retainedFolder=String(draft.folder ?? folders[0] ?? '.');
 const folderOptions=[...new Set([...folders,...(folders.includes(retainedFolder)?[]:[retainedFolder])])].map(folder=>'<option value="'+h(folder)+'"'+(folder===retainedFolder?' selected':'')+'>'+h(folder)+(folders.includes(folder)?'':' — '+h(t('folder_error')))+'</option>').join('');
 const markdown=base ? '<section class="surface toolbox-conversion"><h2>'+h(t('content_category'))+'</h2><h3>'+h(t('markdown'))+'</h3><p>'+h(t('markdown_help'))+'</p>'+(model.capture_paused?'<p class="callout warn">'+h(t('capture_paused'))+' '+moduleLink+'</p>':'')+'<form method="post" action="'+base+'/toolbox/markdown" data-draft-protect><input type="hidden" name="csrf" value="'+h(options.csrfToken)+'"><input type="hidden" name="request_key" value="'+h(draft.request_key)+'"><label>'+h(t('url'))+'<input name="url" type="url" required maxlength="2048" value="'+h(draft.url ?? '')+'"></label><label>'+h(t('folder'))+'<select name="folder">'+folderOptions+'</select></label><label>'+h(t('name'))+'<input name="name" required maxlength="120" value="'+h(draft.name ?? 'public-page')+'"></label><button class="action-button"'+(model.capture_paused?' disabled':'')+'>'+h(t('prepare_markdown'))+'</button></form><a class="text-link" href="'+base+'#project-add-material">'+h(t('source_option'))+'</a></section>':'';
 const notice=model.notice_key ? t(model.notice_key):model.notice;
 return '<!doctype html><html lang="'+normalizeUiLocale(options.locale)+'" '+(options.htmlAttributes ?? '')+'><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>'+h(t('title'))+' · '+UI_DISPLAY_NAME+'</title><style>'+uiStyles()+'</style>'+renderUiClientScript(true)+'</head><body><div class="app-shell">'+renderNav('Toolbox',{...options,project:model.project,interactive:true})+'<div class="workspace">'+renderTopbar({section:t('title'),project:model.project,locale:options.locale,languageCatalog:options.languageCatalog})+'<main class="page toolbox-page"><div class="page-intro"><div><h1>'+h(t('title'))+'</h1><p class="lede">'+h(t('help'))+'</p></div><a class="action-button action-button-secondary" href="'+(base ?? '/projects')+'">'+h(t('project_exit'))+'</a></div>'+(notice?'<p class="callout warn" role="alert">'+h(notice)+'</p>':'')+'<section class="surface"><h2>'+h(t('table_category'))+'</h2>'+table+'</section>'+markdown+'</main></div></div></body></html>';
}
