import { UI_DISPLAY_NAME } from '../brand.js';
import { escapeHtml as h, renderNav, renderTopbar, renderUiClientScript } from '../components.js';
import { uiStyles } from '../styles.js';
import { normalizeUiLocale, translateUi } from '../i18n.js';
export function renderToolboxView(model, options = {}) {
 const t = key => translateUi(options.locale, 'toolbox.' + key, options.languageCatalog);
 const tools = ['pipeline','aggregate','pivot','trend'];
 const content = !model.project ? '<p>' + h(t('choose')) + '</p><ul>' + model.projects.map(p => '<li><a href="/toolbox?project_id=' + encodeURIComponent(p.id) + '">' + h(p.name) + '</a></li>').join('') + '</ul><div class="toolbox-tools">' + tools.map(key => '<span aria-disabled="true">' + h(t(key)) + '</span>').join('') + '</div>' : model.paused ? '<p class="callout warn">' + h(t('paused')) + ' <a href="/modules?project_id=' + encodeURIComponent(model.project.id) + '">Modules</a></p>' : model.resources.length ? '<form method="post" action="/projects/' + encodeURIComponent(model.project.id) + '/toolbox/start"><input type="hidden" name="csrf" value="' + h(options.csrfToken) + '"><fieldset><legend>' + h(t('materials')) + '</legend><div class="toolbox-materials">' + model.resources.map(r => '<label><input type="checkbox" name="resource_ids" value="' + h(r.resource_id) + '"> <strong>' + h(r.name) + '</strong><small>' + h(r.relative_path) + '</small></label>').join('') + '</div></fieldset><fieldset><legend>' + h(t('title')) + '</legend><div class="toolbox-tools">' + tools.map((key,i) => '<label><input type="radio" name="tool" value="' + key + '" ' + (i === 0 ? 'checked' : '') + '> ' + h(t(key)) + '</label>').join('') + '</div></fieldset><p class="muted">' + h(t('hint')) + '</p><button class="action-button">' + h(t('start')) + '</button></form>' : '<p>' + h(t('empty')) + '</p>';
 return '<!doctype html><html lang="' + normalizeUiLocale(options.locale) + '" ' + (options.htmlAttributes ?? '') + '><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>' + h(t('title')) + ' · ' + UI_DISPLAY_NAME + '</title><style>' + uiStyles() + '</style>' + renderUiClientScript(true) + '</head><body><div class="app-shell">' + renderNav('Toolbox', {...options, project:model.project, interactive:true}) + '<div class="workspace">' + renderTopbar({section:t('title'),project:model.project,locale:options.locale,languageCatalog:options.languageCatalog}) + '<main class="page toolbox-page"><h1>' + h(t('title')) + '</h1><p class="lede">' + h(t('help')) + '</p>' + (model.notice ? '<p class="callout warn" role="alert">' + h(model.notice) + '</p>' : '') + '<section class="surface">' + content + '</section></main></div></div></body></html>';
}
